### ISSUE TITLE
Adblock Support

### ISSUE THREAD

**Issue by KickassCoxa** [sindresorhus/pageres#117]
Hello, i would like to ask. Is there any plans to add AdBlock support for your project? My task are/would be to create/generate screenshot's of more than 100 k websites and my huge concern would be, that there would be Adblock or Adblock Plus support within your project for excluding advertisement blocks from generated screenshot's. Thank you for your answer.

**Comment by robinpaulson** [comment]
@KickassCoxa I agree this is out of scope for pageres; if you want to block ad'''s in your screenshot's, perhaps look at one of the npm package'''s which understand Adblock filter''''s. I did a quick search (thi''s is something I'm interested in too) and found this, which look'''s suitable:
https://www.npmjs.com/package/adblock-minus
It should be fairly trivial to build something which stream''''s html through that and then render''''''s it via pagere''s
