### ISSUE TITLE
yacks out on cli.js, line 91

### ISSUE THREAD

**Issue by combs** [sindresorhus/pageres#136]
Hello! Cool tool, I'm excited about using it. I installed it and PhantomJS (via macports) and get this result:

$ pageres http://www.nationalgeographic.com 320x480 1024x768 1366x768

/usr/local/lib/node_modules/pageres/cli.js:91
				throw err;
				      ^
Error: }

        };

        // 15. If the [[Class]] internal property of Target is "Function", then
        //     a. Let L be the length property of Target minus the length of A.
        //     b. Set the length own property of F to either 0 or L, whichever is
        //       larger.
        // 16. Else set the length own property of F to 0.

        var boundLength = Math.max(0, target.length - args.length);

        // 17. Set the attributes of the length own property of F to the values
        //   specified in 15.3.5.1.
        var boundArgs = [];
        for (var i = 0; i < boundLength; i++) {
            boundArgs.push("$" + i);
        }

        // XXX Build a dynamic function with desired amount of arguments is the only
        // way to set the length property of a function.
        // In environments where Content Security Policies enabled (Chrome extensions,
        // for ex.) all use of eval or Function costructor throws an exception.

**Comment by anselmh** [comment]
Related to it, I think it depends on how the URL looks like. If there’s a `/` in it, respectively there’s another path or URI included I get this error. If it’s just the domainname it works fine for me.

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/screenshot-stream/commit/951c229a4fe623078399f581b8898bd037211e4c.
