### ISSUE TITLE
Google font

### ISSUE THREAD

**Issue by wanybae** [sindresorhus/pageres#143]
First Thank you very much for this.

I used last time but it dose not display google font.

``` html
<link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,300'>
```

but result image dose not display Open Sans font.. 
If you know this already I am so sorry.

**Comment by steoo** [comment]
I've the same problem, using phantomjs 1.9.2-6 installed locally and pageres installed locally, and also globally it is not working.
