### ISSUE TITLE
memoize-async throwing exception when ECONNRESET occurs

### ISSUE THREAD

**Issue by chiefy** [sindresorhus/pageres#151]
So I am running into this on Windows 8.1 x64 w/ node latest. I suppose one of the URL's I am hitting his causing it, but is there any way to catch an error w/ one URL and continue?

```
D:\MadGlory\cap\node_modules\pageres\node_modules\memoize-async\index.js:91
        throw err;
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
```

**Comment by kevva** [comment]
@chiefy ping.

**Comment by chiefy** [comment]
@kevva sorry. So yeah I guess my point wasn't so much that an exception was getting thrown, but I was trying to write a script that takes an input of a bunch of site URLs and then loops through them and grabs a screenshot. What is happening is that I have no way of catching that exception (correct me if I am wrong). I was working on a possible solution, but haven't had a chance to finish.

**Comment by sindresorhus** [comment]
@chiefy He was pinging for this:

> Can you please include the full stacktrace (meaning the full output from the terminal)?

We need the full stacktrace to debug this.

**Comment by kevva** [comment]
@chiefy, are you still seeing this?

**Comment by chiefy** [comment]
@kevva I haven't had a chance to really get into it, so I will close. Thanks for pinging me though.
