### ISSUE TITLE
Webfonts

### ISSUE THREAD

**Issue by CarlosSouza** [sindresorhus/pageres#152]
Hi!

Firstly I'd like to thank you for this amazing tool :)

I'm trying to take screenshots of my website (coopers.pro), but it uses @font-face and pageres isn't working properly with that (showing a default Mac OS font instead).

I already checked other posts and you said that it needs phantomjs v1.9.2-6. However, pageres auto installed phantomjs 1.9.8 by itself.

How can I "downgrade" phantomjs to 1.9.6 in order to make webfonts work?

**Comment by sindresorhus** [comment]
Ah, yes, looks like this was regressed when we switched to the `screenshot-stream` module. https://github.com/kevva/screenshot-stream/commit/6117d1d7c3a72180557c90a9f820835190f6dd56 https://github.com/kevva/screenshot-stream/commit/7d389433875574bda80d521f831c4dd62ba23f1c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R27 (both using `^` so it will fetch newer versions).

Should be fixed now though. Just reinstall pageres ;)

// @kevva

**Comment by CarlosSouza** [comment]
Thanks!

But now I'm getting this error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

Do I need to install PhantomJS manually?

**Comment by sindresorhus** [comment]
Look at the terminal output. npm might have failed the install at some point. Try `npm cache clean` and try reinstalling again.

**Comment by CarlosSouza** [comment]
Well I tried installing phantomjs manually then reinstalling pageres and it worked flawlessly.

Thank you for your support! :+1:
