### ISSUE TITLE
Default resolution

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pageres#153]
Sometimes I just want a screenshot without having to care about the size. I propose we add a default size if missing. Which size though? Most popular?

From `npm i -g get-res && get-res`:

1. 1366x768
2. 1024x768
3. 1920x1080
4. 1280x800
5. 768x1024
6. 1280x1024
7. 1600x900
8. 1440x900
9. 360x640
10. 320x568

I like `1366x768`.

**Comment by kevva** [comment]
+1.
