### ISSUE TITLE
Screenshot image output size

### ISSUE THREAD

**Issue by hugsbrugs** [sindresorhus/pageres#155]
Hello,

is it relevant to ask for an option setting a different output image size from screenshot resolution ?

Example : I want a screenshot of 1280x1024 but want the final image to be 160x128 ...

Thanks for highlighting me ...

**Comment by kevva** [comment]
Not going to implement since it will introduce some dependencies like [node-canvas](https://github.com/Automattic/node-canvas) which might fail to install if you don't have all libs installed on your system.

You could easily use a tool like convert to resize your images.

**Comment by hugsbrugs** [comment]
OK, thanks for quick explanation !

**Comment by sindresorhus** [comment]
```
$ convert -resize 50% image.png resized-image.png
```
