### ISSUE TITLE
OSX: vanilla install; command not found

### ISSUE THREAD

**Issue by lubomski** [sindresorhus/pageres#160]
Hi,

I've just done an install of homebrew, node and npm. I then ran ```npm install -g pageres``` and had a successful installation. Upon writing a file to catalog my screenshots and using ```sh takescreenshots``` I get a message of ```pageres: command not found```

contents of 'takescreenshots' is as follows:

```
pageres [ localhost/website/index.html 992x1000 768x1000 480x500 320x500 ]
```
I've checked my $PATH which seems to be okay; other npm packages (such as 'request' run fine using command ```node test.js```)

contents of ```echo $PATH```:

/Users/USERNAME/local/node/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin

Any ideas?

**Comment by sindresorhus** [comment]
https://www.google.com/search?q=npm+command+not+found

**Comment by mikeyakimenko** [comment]
Just update OS X to El Capitan, and same problem. with PATH and other things everything ok, even if i install bower or grunt -g all works. 

Pageres doesn't work on El Capitan.

**Comment by kevva** [comment]
`npm install --global pageres-cli`
