### ISSUE TITLE
Allow other formats other than PNG

### ISSUE THREAD

**Issue by mugendi** [sindresorhus/pageres#162]
PNG is great for vector graphics but not always the best for raster graphics.I have a project that required JPEG image captures and had to edit /lib/util.js to allow for dynamic image format settings rather than the hard-coded PNG format.

It would be nice to allow for that flexibility and all that's needed is an edit on line 141 to:
var filename = _.template(options.filename + **'.'+options.format**, {

**Comment by kevva** [comment]
Duplicate of https://github.com/sindresorhus/pageres/issues/129. Use `--format jpeg` if you're using the CLI or `format: 'jpeg'` if you're using the API directly.

**Comment by sindresorhus** [comment]
@kevva Maybe we should document it?

**Comment by kevva** [comment]
Probably.

**Comment by kevva** [comment]
@sindresorhus, I've added a fix for accepting `jpg` as format. Could you fix the documentation here :)))?

**Comment by sindresorhus** [comment]
Done in https://github.com/sindresorhus/pageres/commit/0f32f7e8152dd32448b6e1db8b3131a1c6ee6371

**Comment by mugendi** [comment]
@sindresorhus @kevva thanks guys!
