### ISSUE TITLE
SVG not displayed

### ISSUE THREAD

**Issue by asitemade4u** [sindresorhus/pageres#164]
Hi,
Thank you for this Grunt package that allows us to nail down responsiveness issues on the websites we develop!

The only thing that seems not to be working is that the embedded SVG files do not seem to be displayed:here is an example as drawn by Grunt:Pageres:
![320x480-127 0 0 1 8080 cda cda-drawing how-to-break-daddy-and-papas-tv-remote-control](https://cloud.githubusercontent.com/assets/11460106/6739133/19e88eae-ce4d-11e4-8ae3-1e49623373b8.png)

Here is the page it comes from: http://boysinburbs.com/cda-drawing/how-to-break-daddy-and-papas-tv-remote-control/

Some details:
- the page we tested was hosted on a local server accessed by 127.0.0.1:8080 [but this should not be an issue]
- the website is a WordPress website
- there is a Lazy Page script [WP plugin] allowing to display the pictures progressively [this might be the culprit].

Best,
Stephen

**Comment by sindresorhus** [comment]
You might want to try the [`delay`](https://github.com/sindresorhus/pageres#-d---delay) option as the SVG might have been loaded async. Pageres only waits on the page load event, but there still might be other stuff being lazy loaded afterwards. No way for Pageres to know about that.

**Comment by knight444** [comment]
Hmmdhdomo
ilggggggggggggggggggggggggggggoooooooolhkfhklhlkfhlllllllllllllllllllffmkmmfm.kmhkhmkkmmhmkmmmhffkkkkkkhkhkkkfkhkkkkmmfmmmmmfmhmmhmmhmfmmhmmmmmkkkkhmhkkkffkkkkkmddkkdddddkkdddllllPl
Lddldddlddddddddddddddddddddddddddddddddddlddddllllm
kkkkhmhkkkffkkkkkmddkkdddddkkdddllll
KLLL
KLLL

Llllmmlmklklllllllllllllll l l

L
L l


Llllllllllllllllllllllll
llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllLlllllllllllllllllllllll
Llllllllllllllllllllllll Llllllllllllllllllllllll

M
m
lll l lkkm

Lmmkkkkkkkkkkkkllkkkmkkkkkkkkllmkk lo
Mllkdkkhdlmlm
Llllllllllllllllllllllll
Lllllllllgggg
Z
k
GSTAAD ppppo irritación Itty a tu
aiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasassaaaaaaaassaaaaaahhhhhi ji ihi ihi u
ihi ihi I hiu ihiiiii juju iiiiiiiiiiiiiiiiiiiiiiuiuiiii u iuuuuiiii I
uuuiiii hi iiuuiii u iiiiiiiiiiiiiiiiiiiii ihi iuihiuiiiuuu I uiuuuuuuuuuuu
Uruguay

**Comment by asitemade4u** [comment]
Thanks!
