### ISSUE TITLE
Always taking screenshot of Sign-in page

### ISSUE THREAD

**Issue by karan4336** [sindresorhus/pageres#165]
I have a website in local dev-box.
I have tried to take screen-shots of several pages of the website (for all these pages we need to be logged into the site). But it always takes screenshot of sign-in page.

I am trying the following command 
$ pageres http://localhost:9000/#/deviceList 1024x768  --username 'test1' --pasword 'test1234'.

Any help to resolve it will be highly appreciated.

P.S. : I cannot upload screenshots here because of the confidentiality clause of website under development.

**Comment by kevva** [comment]
You need two `s` in `password`.

```
$ pageres http://localhost:9000/#/deviceList 1024x768 --username 'test1' --password 'test1234'
```

**Comment by karan4336** [comment]
it was just a typing error. The issue still persists even after using two s. Kindly suggest any other way to resolve it.

**Comment by kevva** [comment]
Then you haven't logged in correctly. It's just creating a header with basic authorization https://github.com/kevva/screenshot-stream/blob/master/lib/index.js#L22. There's no guarantee that it will work everywhere.

**Comment by smurfpandey** [comment]
@karan4336 This will only work if authorization is done via Authorization Headers, otherwise you can look into adding auth-cookies
