### ISSUE TITLE
Running Pageres with PHP exec

### ISSUE THREAD

**Issue by WeathermanMatt** [sindresorhus/pageres#167]
Hello,

I'm using Pageres to capture a Highcharts chart. I have a PHP script that takes in an argument to generate the proper URL and file name for the pageres command. When I go to use PHP's exec command, it fires off a bunch of pageres commands and never actually completes the pageres command. The pageres command works perfectly from the command line though.

Snippet of my PHP code:
`$cmd = "pageres [http://localurl/wriphp/visGraph.php?port=".$port." 1100x200 --filename ".$port."]";`
`exec($cmd);`

Why does the php exec call run out of control?

**Comment by kevva** [comment]
This is ultimately a PHP issue and is probably better asked on StackOverflow. I suspect your script is treated as a non TTY and therefore pageres [expects](https://github.com/sindresorhus/pageres/blob/master/cli.js#L201-L204) it to pipe in stuff. Have you tried `shell_exec`?

**Comment by WeathermanMatt** [comment]
Thank you very much for the quick response. I will post this over on StackOverflow and see if anyone else has input. Thank you for the tip on the non TTY -- I'll look into that. I have tried the `shell_exec` and I have the same issue.

**Comment by kevva** [comment]
Make sure you've read the comments on [php.net](http://php.net/manual/en/function.shell-exec.php#106250) too. Hope you'll find a way to run it successfully!
