### ISSUE TITLE
If multiple paths given in url.txt generating blank images except for the last url

### ISSUE THREAD

**Issue by karan4336** [sindresorhus/pageres#168]
Sorry to bother u again!!

But unfortunately nothing seems to be working for me. So i request you to give detailed answer this time.
I using the following command
pageres --delay 3 1024x768 < urls.txt (on a windows command prompt).

In urls.txt, I have something like this
C:\Users\karan\project\views\products\product.html
C:\Users\karan\project\views\sub-products\sub-product.html

2 png files are generated but the png file for only last path is having data rest all are blank.
I have tried with multiple combinations, but always only last path displays the correct image for all the mentioned urls and rest all images are blank.

i tried to upload my input file, but unfortunately .txt format is not supported.

Any help on this issue will be much appreciated.

**Comment by kevva** [comment]
Does it work with remote URLs? I've just tried (on Windows) using a file with 10 URLs and all rendered fine.

**Comment by karan4336** [comment]
yes it is working fine with remote urls. So what could be the issue with local paths?

**Comment by kevva** [comment]
Should be fixed now!

**Comment by karan4336** [comment]
yes it is working now!!
Thanks
