### ISSUE TITLE
strategy for running grunt-pageres multiple times?

### ISSUE THREAD

**Issue by fkh** [sindresorhus/pageres#169]
I'm trying to capture screenshots of an arbitrary list of URLs using grunt and pageres. 

I have a gruntfile that gets the list of URLs, but I am not sure how to set up a number of pageres tasks from that list. [Here's what I have](https://github.com/fkh/civic-archive/blob/54d4f85b9f3451b7bd9fece7ac0fef9eb9ff0876/Gruntfile.js), which doesn't work, because it's passing the entire list of URLs to the url config that expects a single parameter. 

Thanks in advance - I appreciate that this is more of a generic Grunt strategy question than specifically about pageres...

**Comment by sindresorhus** [comment]
No idea why you're using grunt for this as it would be much simpler as just a node script or gulp. But if you insist on using grunt you'll have to dynamically generate the grunt config.

Something like:

```js
var targets = {};

[
	'https://google.com',
	'https://github.com'
].forEach(function (el, i) {
	var target = targets['target' + i] = {};

	target.options = {
		url: el,
		sizes: ['1200x800'],
		dest: 'dist'
	};
});

grunt.initConfig({
	pageres: targets
});
```
