### ISSUE TITLE
Support sessionStorage JWT token authentication?

### ISSUE THREAD

**Issue by sashton-stoneware** [sindresorhus/pageres#173]
A common use case nowadays is to store JWT tokens in sessionStorage (and localStorage) to authenticate users via AJAX calls. A good explanation of the approach and its rationales can be found [here](https://auth0.com/blog/2014/01/07/angularjs-authentication-with-cookies-vs-token/). And the approach appears to be [growing](https://www.google.com/trends/explore#q=cookie%20authentication%2C%20jwt%20token&cmpt=q&tz=).

Is there interest in supporting this?

**Comment by kevva** [comment]
Is it `authorization: 'Bearer ' + TOKEN` you're asking for?

**Comment by sashton-stoneware** [comment]
Yes, ultimately that is what I'm looking for. In frameworks like AngularJS, what typically will happen is the framework will read sessionStorage for the token on page load, then declare an XHR request interceptor via Javascript to make sure that the header is attached to all outgoing XHR requests. 

In this case then, what would make most sense? (1) have pagres itself attach the bearer token to all outgoing XHR requests or (2) to set the token in sessionStorage then allow the executing Javascript to read the token from sessionStorage and create the XHR interceptor itself?  

I do know in many use cases the second option would probably be more robust since the Javascript also will sometimes do other things with the token in sessionStorage, like checking for its existence before performing "logged in" logic.

**Comment by kevva** [comment]
We've added support for setting custom headers a while ago which should fix this. https://github.com/sindresorhus/pageres#headers.
