### ISSUE TITLE
Scale parameter does not work for values less than one

### ISSUE THREAD

**Issue by vcernomschi** [sindresorhus/pageres#177]
I am taking the screenshot with size '800x450', but I should scale them in 5 times less than the original image.

Can you please assist me if I am able to do scale images to decrease theirs sizes.

For example, 
var pageres = new Pageres({delay: 2, scale: 0.2, crop: true}).src(domainName, [defaultSize], {filename: fileName});

Note: Scale to increase image works fine.

**Comment by kevva** [comment]
We have restricted it to only support scaling to increase the image size. See https://github.com/kevva/screenshot-stream/blob/master/index.js#L15. @sindresorhus, does it makes sense to support both?

**Comment by sindresorhus** [comment]
@kevva I don't see a reason to limit it.

**Comment by kevva** [comment]
Must've been a reason for it. Oh, anyway. Going to change it.
