### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by thiagupct** [sindresorhus/pageres#178]
Script generating Event listener warning when used in a loop of more than 10 websites/devices.
```javascript
//Express server settings for static content delivery
app.use(express.static(__dirname));   

app.get('/', function (req, res) {
    res.sendFile(__dirname + '/home.html');
});

//Socket.io start-up process
io.on('connection', function(socket){
    socket.on('message', function(uri){
        console.log(socket.listeners('message').length); //returning 1 as length
        iterate(uri);
    });
});

//Process website url, save image and find its responsiveness
function snapshot(url, width, device, agent){  
	var path = device+'_'+width+'x'+320+'-'+new Date().getTime();
	var pageres = new Pageres({delay: 2})
    .src(url, [width+'x'+320], {filename: path, userAgent: agent})
    .dest(__dirname+'/static/images/');

	pageres.run(function (err) {
        if(err){
            console.log(err);
        }else{
	        .....
	        io.emit('image', path, false);
	    }
    });
}

//Helper function for image processor
function iterate(url) { 
       ....
        snapshot(url, width, device, user_a[i]);
        io.emit('load', width, device);
}

console.log('Open localhost with port 8080');
```
```javascript
(node) warning: possible EventEmitter memory leak detected. 11 SIGINT listeners
added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:179:15)
    at process.on.process.addListener (node.js:668:26)
    at Pageres.exports.save (C:\Nodejs\node_modules\pageres\lib\util.js:101:10)
    at Pageres.<anonymous> (C:\Nodejs\node_modules\pageres\index.js:134:8)
    at callback (C:\Nodejs\node_modules\pageres\node_modules\each-async\index.js
:38:4)
    at C:\Nodejs\node_modules\pageres\node_modules\each-async\node_modules\oneti
me\index.js:20:12
    at Pageres.<anonymous> (C:\Nodejs\node_modules\pageres\index.js:118:3)
    at Immediate.immediate._onImmediate (timers.js:409:16)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
Any help is appreciated. Thanks in advance.

**Comment by thiagupct** [comment]
```javascript
process.on('SIGINT', end.bind(null, process.exit));
```
on
```javascript
C:\Nodejs\node_modules\pageres\lib\util.js
```
causes this event listener warning, after commenting out the script feels to be working fine. Don't know whether this may create some other issue. Please check and confirm.

**Comment by kevva** [comment]
Could you provide a test repo?

**Comment by thiagupct** [comment]
@kevva Please use [this repo](https://github.com/thiagupct/pageres) with pageres. This generates the possible EventEmitter memory leak warning.

**Comment by kevva** [comment]
✔ Generated 1 screenshot from 1 url and 1 resolution

**Comment by n370** [comment]
I'm having the same issue trying to put this project together.

Here's the part where I think I'm doing things wrong.
https://github.com/tevincocin/pagebag/blob/master/main.js#L74-L87

I appreciate any help.

**Comment by sindresorhus** [comment]
Don't really know why it's happening, but you can work around it by setting this in your code:

```js
require('events').EventEmitter.defaultMaxListeners = Infinity;
```

**Comment by n370** [comment]
Hey @sindresorhus thanks for addressing this one personally.

While I was waiting for this answer I dug a little bit further on the web for answers and came up with an almost working solution.

I checked out a previous commit and swapped async.parallel for async.series at the following line.

https://github.com/tevincocin/pagebag/blob/4f898d8939f540b0a786586d3b2282688a537601/main.js#L89

Unfortunately after running this modified version I got it working just for while. This time the thing seemed weirdier to me as it looked like it was going to work flawlessly, even capturing a couple of screenshots more after the error popped up.

I feel I must add that the array of urls I'm using to test locally has more than ten thousand entries.

I'll try now setting the defaultMaxListeners to infinity. Let's see if it gives me a chance.

**Comment by sindresorhus** [comment]
To actually fix this, we need to track down where we subscribe to the "too many events" and set that emitter to `emitter.setMaxListeners(Infinity);`. We can't use the above hack as it applies to all running code.

**Comment by n370** [comment]
Yep, you're right.

But let me reword my last comment a little bit because I guess my lazyness confused you, I' sorry about that. 

The version that worked weirdly was the one I hacked locally replacing parallel for series. So with async.parallel code explodes (a) and with async.series code behave weirdly than explodes (b).

Now setting defaultMaxListeners to infinity makes the code work as it worked without it but now it never explodes, instead it just hangs forever (c).

(a) https://github.com/tevincocin/pagebag/blob/4f898d8939f540b0a786586d3b2282688a537601/main.js
(b) https://github.com/tevincocin/pagebag/blob/00e2328d79feea719402a19a269b4209446b8bb3/main.js
(c) https://github.com/tevincocin/pagebag/blob/8072012250d6e4bd53ee80718de00e7752402e09/main.js

I hope I'm leaving no space for misunderstandings now. Thanks again and let us know if you have any news about how to actually fix it.

**Comment by n370** [comment]
Just stumbled upon this blog post outlining a few strategies to fix node.js memory leaks http://www.toptal.com/nodejs/debugging-memory-leaks-node-js-applications

Haven't tried though, just sharing.

**Comment by sindresorhus** [comment]
Is this still an issue on latest Node.js and the latest version of Pageres?

**Comment by n370** [comment]
_node v5.5.0_
_pageres v4.0.0_ 

I'm passing a big (500kb) JSON file with over 10.000 urls. This doesn't seems to be an issue with node or pageres. I think it's more related to how I am approaching the idea.

https://github.com/tevincocin/pagebag/commit/a0d290271d4b67980b35e1774ebc5ad80acdbcf4

```bash
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/n370/Projects/Tevincocin/pagebag/node_modules/phantomjs/lib/phantom/bin/phantomjs EAGAIN
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by silverwind** [comment]
I still see this leak, exactly after 11 pageres runs. Here's something to reproduce:

````console
$ node -v
v6.0.0
$ cat node_modules/pageres/package.json | jq -r .version
4.1.1
````
````js
"use strict";
const Pageres = require("pageres");

(function next(i) {
  console.log("run #" + ++i);
  new Pageres().src("google.com", ["1366x768"]).dest("/dev/null").run().then(next);
})(0);
````
````console
$ node test.js
run #1
run #2
run #3
run #4
run #5
run #6
run #7
run #8
run #9
run #10
run #11
(node:6172) Warning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
````

**Comment by silverwind** [comment]
Filed https://github.com/sindresorhus/pageres/pull/257.
