### ISSUE TITLE
pageres can not work with windows security authority

### ISSUE THREAD

**Issue by xiangdewei** [sindresorhus/pageres#181]
Hi, 

I have a problem that when I use pageres to capture a webpage, and this page need windows security autority,and the userName is looks like "domain\name" and password looks like  "password".

pageres can not load this kind of url. but can load no "domain" pages.

is this a bug?
I need your help.

thank you.
Simon

**Comment by kevva** [comment]
How does the URL look like?

**Comment by xiangdewei** [comment]
It looks like http://example:8000/zh-cn/education/default.aspx#fbid=Jv41IrLc9tx

**Comment by xiangdewei** [comment]
Hi kevva, 

I looked for some documents and I found that:

1. pageres can work good in HTTP Authentication Basic, the Authorization request header looks like :Authorization: Basic aHR0cHdhdGNoOmY=
and the Encryption method is a base64 encoded version of <username>:<password>
2.pageres can not work in windows Authentication, the Authorization request header looks like :Persistent-Auth:true
and the Encryption method is  the client browser sends a strongly hashed version of the password in a cryptographic exchange with your Web server.

Does pageres  can dicide which kind of Authentication and Encryption method  to use?

looking forward your reply.

Simon
2015/5/20

**Comment by kevva** [comment]
@sindresorhus, wdyt about adding support for custom headers?

**Comment by sindresorhus** [comment]
Yeah, I guess we could http://phantomjs.org/api/webpage/property/custom-headers.html

**Comment by kevva** [comment]
https://github.com/kevva/screenshot-stream/blob/master/lib/index.js#L20-L24, but we should just expose a `headers` option.

**Comment by sindresorhus** [comment]
Yeah. And on the CLI it should be `pageres --header="Foo: bar" --header="Foo2: bar2"` (notice singular).

**Comment by kevva** [comment]
@sindresorhus, can you document the `headers` option in here and `--header` at pageres-cli and do a version bump? There should be support for it now.
