### ISSUE TITLE
delay is not working

### ISSUE THREAD

**Issue by sud201449** [sindresorhus/pageres#183]
I'm trying to set delay as option but screenshot is not considering the delay. I think it may related to phantomjs
         i'm using phantom version 1.9.7 on windows 7.

**Comment by kevva** [comment]
Do you have any code or something we can test?

**Comment by sud201449** [comment]
pageres --delay 10 1366x768 https://www.mackenzieinvestments.com/en/prices-performance?w_state=deY6hyYooIZGYY9LXj0L9D8MqYe6dXk1psMiCY5Y9eW&w_hash=5f96eecabbc6f268a6a3292286a601ae 

          There is ajax calls and will load the third tab after some seconds but screenshot contains first tab before page refresh

**Comment by kevva** [comment]
I can reproduce it, but I don't think it's an issue with `pageres`, more so with PhantomJS.

**Comment by sindresorhus** [comment]
Yeah, sounds like a PhantomJS issue. Delay works fine in other cases. I just used it for something else.

Closing in favor of https://github.com/sindresorhus/pageres/issues/77 as there isn't much we can do until that's resolved.
