### ISSUE TITLE
Pseudo Classes rendering issue

### ISSUE THREAD

**Issue by jbrad** [sindresorhus/pageres#184]
I am seeing some issues rendering pseudo classes in the screenshots produced. I'm not sure if it's something with this module or PhantomJS. 

Anyone else see this or have any thoughts?

![pseudo-classes](https://cloud.githubusercontent.com/assets/402819/7755964/870f3ef0-ffbd-11e4-8814-553f733dd8c6.png)

**Comment by sindresorhus** [comment]
The WebKit version in PhantomJS 1 is more than 3 years old, so I'm not surprised. We're just waiting for PhantomJS 2 to be usable. https://github.com/sindresorhus/pageres/issues/77
