### ISSUE TITLE
100% coverage

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pageres#186]
Now that we have coverage checking we should get it to 100%.

https://coveralls.io/r/sindresorhus/pageres

We just run the following and dig into the report:

```
npm run coverage -- --reporter=lcov
```

---

Pull requests to improve this would be much appreciated :rabbit:

**Comment by kevva** [comment]
Some of them is really hard to cover.

**Comment by SamVerschueren** [comment]
It's possible to stub the `utils.create` method to throw an error and get 100% coverage in `index.js`. This is the same case for `utils.js`. A lot of them only require to stub a method in order to return an rejected callback.

I started with this in the [ES2015 branch](https://github.com/sindresorhus/pageres/pull/212), not sure when this one will be merged to master?

Another issue I am experiencing is that the coverage report is not correct. Is it possible to use nyc with AVA today?

**Comment by sindresorhus** [comment]
> It's possible to stub the utils.create method to throw an error and get 100% coverage in index.js. This is the same case for utils.js. A lot of them only require to stub a method in order to return an rejected callback.

:+1: 

> Another issue I am experiencing is that the coverage report is not correct. Is it possible to use nyc with AVA today?

Not sure tbh. It should, but haven't tested.

**Comment by SamVerschueren** [comment]
Coveralls is returning the correct coverage report so it should be working I guess.

**Comment by sindresorhus** [comment]
Actually, it's not working, latest commit there is from august https://coveralls.io/github/sindresorhus/pageres

**Comment by SamVerschueren** [comment]
I pointed this out some time ago here: https://github.com/sindresorhus/ava/issues/28.

**Comment by SamVerschueren** [comment]
Apparently [got](https://github.com/sindresorhus/got) is able to run coverage reports with nyc and AVA.

**Comment by sindresorhus** [comment]
@SamVerschueren `got` is using an unreleased version of AVA. Let's get back to this after the next AVA release.

**Comment by SamVerschueren** [comment]
Good to know it's coming! :)

**Comment by SamVerschueren** [comment]
@sindresorhus Any idea why coveralls isn't being updated?

**Comment by sindresorhus** [comment]
Managed to narrow it down: https://github.com/sindresorhus/pageres/commit/f175067f763a6733794db1906fe8d6a6045b612c

Looks like those 4 tests are making `nyc` not report anything (by just showing 100% without any files).

No idea why, though. Might be a bug in the code somewhere. 

At least it reports coverage again: https://coveralls.io/builds/3955628

**Comment by SamVerschueren** [comment]
I found out that `nyc` is not reporting in the following situations

1. When multiple screenshots are taken for one website.
    - `await new Pageres().src('yeoman.io', ['w3counter']).run()`
    - `await new Pageres().src('yeoman.io', ['480x320', '1024x768', 'iphone 5s'])`

2. If a filename is provided
    - `await new Pageres().src('http://todomvc.com', ['1024x768'], { filename: '<%= date %> - <%= time %> - <%= url %>'}).run()`

These are my first observations, will continue digging.

**Comment by sindresorhus** [comment]
I've noticed that after running the `npm test` and seeing the 100% false output from `nyc`, there's a lot of `phantomjs` processes still running that never quits. Try looking at processes after a run.

**Comment by SamVerschueren** [comment]
Some things I could find regarding the processes

https://github.com/sgentle/phantomjs-node/issues/198
https://github.com/ariya/phantomjs/issues/11390

Seems like we are not the only ones having issues :p.

**Comment by SamVerschueren** [comment]
_from @sindresorhus_

> To support nyc:
> > Source maps are used to map coverage information back to the appropriate lines of the pre-transpiled code. You'll have to configure your custom require hook to inline the source map in the transpiled code. For Babel that means setting the sourceMaps option to inline. - https://github.com/bcoe/nyc#support-for-custom-require-hooks-babel-es2015
