### ISSUE TITLE
Does not work with php exec/ssh on digitalocean

### ISSUE THREAD

**Issue by windows1087** [sindresorhus/pageres#189]
I have an Droplet on Digitalocean. Installs pageres global with npm. When i make an pageres request directly in the terminal, it works...but when i make an exec() over php, it loads and loads, but nothing...i have tried it with SSH from Laravel 4, but same problem :(
    
Any idea?

**Comment by windows1087** [comment]
I tried this:

```
exec('pageres http://google.com 2>&1', $output, $returnCode);
$output = implode(PHP_EOL, $output);
echo $output . ' ' . $returnCode;
```

and become "âœ” Generated 82 screenshots from 1 url and 82 resolutions 0".

It has make 82 screenshots from 82 resolutions, but i need only one :( The same issue i have on local xampp

**Comment by kevva** [comment]
https://github.com/sindresorhus/pageres/issues/167
