### ISSUE TITLE
set default background color

### ISSUE THREAD

**Issue by a1Gupta** [sindresorhus/pageres#192]
I am getting transparent background for screenshot of some websites. There's no option to set default background color. In  PhantomJS I used to do it like this

page.evaluate(function(w, h) {
			document.body.style.width = w + "px";
			document.body.style.height = h + "px";
			document.body.style.backgroundColor = '#ffffff' ;
			}, width, height);

**Comment by sindresorhus** [comment]
That's weird. We already set the background color: https://github.com/kevva/screenshot-stream/blob/master/lib/index.js#L88-L90

Can you share an URL where this is reproducable?

**Comment by a1Gupta** [comment]
I tried to take screenshot of 'http://acer.com'.

Using Pageres
![acer com](https://cloud.githubusercontent.com/assets/5560733/8294878/179f6e6e-195d-11e5-94cf-805048010c74.png)
Using screenshot-stream
![acer com](https://cloud.githubusercontent.com/assets/5560733/8294881/1d32f602-195d-11e5-8814-1a4e6e06c649.png)

Pageres is generating a transparent screenshot where as screenshot-stream is rendering a blank white image.

**Comment by kevva** [comment]
What version of pageres are you using?

**Comment by a1Gupta** [comment]
1.3.10

**Comment by sindresorhus** [comment]
That site seems to load everything after the body ready event and is therefore not captured. Using the `--delay` option makes it work fine.

**Comment by a1Gupta** [comment]
Ok I will try that

**Comment by a1Gupta** [comment]
@sindresorhus How much delay you used. I tried with delay of 60 secs still no white background.

**Comment by SamVerschueren** [comment]
What pageres version are you using? Try upgrading.

**Comment by a1Gupta** [comment]
v4.1.1
This is what I am doing -
```
const pageres = new Pageres({delay: 50})
    .src('acer.com', ['1366x768'], {crop: true, css: 'body { background: white; }'})
    .dest(__dirname+'/output')
    .run()
    .then(() => console.log('done'));
```
But I am getting transparent background.

**Comment by SamVerschueren** [comment]
It is set by pageres (technically by `screenshot-stream`). But have you tried using `!important`? Will have a look when I'm on my computer later today.

**Comment by a1Gupta** [comment]
even that isn't working

**Comment by SamVerschueren** [comment]
This is really weird. When I set the background color for `acer.com`, it does not work and it stays transparent. When I try it with another website, like `yeoman.io` for instance, it works as expected. So it's probably something on the website itself that overrides the background color.
