### ISSUE TITLE
Feature: Support Dynamic Content Loading

### ISSUE THREAD

**Issue by marvinosswald** [sindresorhus/pageres#194]
Maybe as an additional option: Let phantomjs scroll down to the bottom of a site to load js controlled elements triggered by scroll position..

Cheers

**Comment by kevva** [comment]
I guess it's possible but it would require some complex stuff I think. We would need to first scroll to your position and then use [waitFor](https://github.com/ariya/phantomjs/blob/master/examples/waitfor.js). The hard part is to make a usable API for this.

**Comment by sindresorhus** [comment]
Is that really needed though? In PhantomJS isn't the whole document the viewport so dynamic content would be triggered by default as we return the whole document? Can you provide an URL we can test?

**Comment by marvinosswald** [comment]
Nah it doesn't scroll down otherwise it would be triggered anyway. If I remember correctly phantomjs has an api you can use to scroll down... maybe paired with the already existing delay option it should work.


Found on so: http://stackoverflow.com/a/17758165/1577384

Testurl: http://demowp.cththemes.com/lotek/

**Comment by kevva** [comment]
Yes, but if you show the whole page you won't need to scroll down.

**Comment by marvinosswald** [comment]
Sadly no, because especially this site has animations triggered by javascript depending on the scrollbar position which equals the amount of pixels that are hidden from view above the scrollable area.

**Comment by SamVerschueren** [comment]
When providing a width and height, the image works as expected. Probably because like @kevva mentioned, the viewport is set to these dimensions which will trigger the script to load the animations.

```
$ pageres http://demowp.cththemes.com/lotek/ 1800x7150
```

Not sure how PhantomJS takes those screens when no viewport is set.

**Comment by boban984** [comment]
@SamVerschueren that works as expected, i also get a good shot of the page, i think this issue should be closed

**Comment by sindresorhus** [comment]
> Not sure how PhantomJS takes those screens when no specific width and height is provided.

If no size is specified, we use a default one, so PhantomJS always gets a size.

**Comment by iamkhalidbashir** [comment]
For websites whose height is not known, we get extra white blank spaces at the end
I think a proper solution would be to animate scroll behaviour
