### ISSUE TITLE
Question: how does PhantomJS gets installed?

### ISSUE THREAD

**Issue by rafaelrinaldi** [sindresorhus/pageres#196]
The docs say that PhantomJS is a dependency but I don't see how it "automagically" gets installed. It's not listed on the `package.json`. So how does it get installed?

**Comment by sindresorhus** [comment]
`pageres` => `screenshot-stream` => `phantom-bridge` => `phantomjs`

https://github.com/sindresorhus/phantom-bridge/blob/23cd7e6f7596b680f990d300d1f0cc22fc2706c5/package.json#L31

**Comment by rafaelrinaldi** [comment]
@sindresorhus Thanks :)
