### ISSUE TITLE
Throw err; Unhandled error event - In Pageres

### ISSUE THREAD

**Issue by rodkeyes** [sindresorhus/pageres#197]
Hey there,
I believe this issue is on Pageres's side, I was trying to screenshot a website and I ran in to this issue of an unhandled error event.

![68ecaa4d9a9d12ad535eb1abf80cbfa5](https://cloud.githubusercontent.com/assets/11384070/8760691/9354a60a-2cf9-11e5-8bf2-fd7130bd76bd.png)

**Comment by sindresorhus** [comment]
It couldn't load the URL. Maybe your internet was down or the site weren't reachable.

-

@kevva The error should be handled by `screenshot-stream` though. It's currently an unhandled error.

**Comment by kevva** [comment]
Hmm, we're just emitting it in `screenshot-stream` ([here](https://github.com/kevva/screenshot-stream/blob/master/index.js#L65)). I believe it should be handled here?

**Comment by kevva** [comment]
@rodkeyes, I think you just need to update `pageres`, or preferably install `pageres-cli`. This is what I'm getting:

```
$ pageres asdasdasdassgdfhfgdh.com
Couldn't load url: http://asdasdasdassgdfhfgdh.com
```

So it seems like we are in fact handling the error.
