### ISSUE TITLE
thumbnails on ubuntu 14.04 with pageres and some other issue in mac

### ISSUE THREAD

**Issue by procoder-net** [sindresorhus/pageres#198]
Hi,

I want to take snapshot of webpage...but when i load in Ubuntu its not loaded at all...it stops in the middle.

        url = 'https://sapui5.netweaver.ondemand.com/test-resources/sap/m/demokit/cart/index.html?responderOn=true#/category/AC';
     var options = {delay:2};
    var pageres = new Pageres(options)
        .src(url, ['1280x1024'], {crop: true})
        .run(function(error, items){
            console.log(items);

            items[0].on('data', function (data) {
                bufferData.push(data);
            });

            items[0].on('end', function () {
                deferred.resolve(Buffer.concat(bufferData));
            });
        });

    pageres.on('warn', function(error){
        console.log(error);
    });

but in Mac its different issue, but eventually i can generate in mac or windows.

even on ubuntu i can generate snapshot of other pages like google.com or any other.

can someone help in understanding why the phantom is not loaded in ubuntu but it loads in mac??

Thanks
Moyeen

**Comment by sindresorhus** [comment]
Can you share any error/output messages?

**Comment by procoder-net** [comment]
Error: found in negative cache: 'sap/ui/core/Core.js' from undefined/sap/ui/core/Core.js: The given language does not adhere to BCP-47. sapui5.netweaver.ondemand.com/resources/sap-ui-core.js:80 in a1 sapui5.netweaver.ondemand.com/resources/sap-ui-core.js:80 sapui5.netweaver.ondemand.com/resources/sap-ui-core.js:144 TypeError: 'undefined' is not an object (evaluating 'new sap.m.Shell') sapui5.netweaver.ondemand.com/test-resources/sap/m/demokit/cart/…

**Comment by procoder-net** [comment]
The same is working on mac...

**Comment by procoder-net** [comment]
can someone help??

**Comment by SamVerschueren** [comment]
It has something to do with the website. I don't think PhantomJS is capeable of rendering it correctly. Not sure why though.

```js
var Pageres = require('pageres');

var url = 'https://sapui5.netweaver.ondemand.com/test-resources/sap/m/demokit/cart/index.html?responderOn=true#/category/AC';

new Pageres({delay: 30})
	.src(url, ['1280x1024'], {crop: true})
	.dest('public')
	.run();
```

It generates a screenshot but the screenshot is just plain white.

I used a delay of 30 seconds just to test it was not caused because of some delay.

**Comment by SamVerschueren** [comment]
Maybe this has something to do with it: https://github.com/SAP/openui5/issues/557

If I'm not mistaken, `Pageres` uses PhantomJS 1.9.
