### ISSUE TITLE
ES2015 and Promises

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pageres#203]
I think we should go all in on this module and use ES2015 and Promises. Need to find a way to easily compile with Babel without too much boilerplate. Promise polyfill: https://github.com/floatdrop/pinkie-promise

PR welcome if anyone wants to try their hand at this.

**Comment by kevva** [comment]
Just running `babel index --out dist.js` should be enough I guess.

**Comment by sindresorhus** [comment]
Yup, and add a "main" field in package.json that points to `dist.js`.

**Comment by sindresorhus** [comment]
Or better yet, `index.src.js` for the ES2015 source and `index.js` for the dist?

**Comment by arthurvr** [comment]
> Or better yet, index.src.js for the ES2015 source and index.js for the dist?

Personally I like `dist.js` more as it's very clear it's the compiled version. `index.js` is the first place I'd look for the actual source.

**Comment by sindresorhus** [comment]
Even if the other file has `src` in its name?

**Comment by arthurvr** [comment]
It's up to you, but I'd generally naively type `vim index.js` and then spot the other file.

**Comment by sindresorhus** [comment]
I'm fine with either. Doesn't really matter.
