### ISSUE TITLE
pageres-cli should recognize single-word urls

### ISSUE THREAD

**Issue by lkraav** [sindresorhus/pageres#204]
Single word is a valid hostname in local configurations. Protocol-based disambiguation should work at the very least.

```
$ [-] pageres --version
1.1.1
$ [-] pageres papaya
⚠ Specify a url
$ [-] pageres http://papaya
⚠ Specify a url
```

**Comment by sindresorhus** [comment]
Yeah, makes sense. This seems to be the culprit: https://github.com/sindresorhus/pageres-cli/blob/df6c1e98caab40592d65f756ea045a05ee304bd2/cli.js#L164 That regex needs to also check for a protocol. PR welcome, if not I'll get to it sometime next week.

Can't support protocoless tld-less URLs as it would conflict with resolution keywords: https://github.com/sindresorhus/pageres#sizes

**Comment by lkraav** [comment]
Can't do anything extracurricular for weeks, so backed up :/

**Comment by portgasd666** [comment]
i think im almost done with fixing this. Do you want me to assume .com when no tld is given ?

**Comment by lkraav** [comment]
Why assume anything at all?

**Comment by portgasd666** [comment]
Okay . I realize I've been understanding the issue wrongly. So where would you have the request go when the input is http://papaya ?

**Comment by lkraav** [comment]
http://papaya is the final url. Nothing else in there. It's a perfectly valid local hostname.

**Comment by portgasd666** [comment]
Yeah I got it . I didn't read your initial message carefully enough to realize that you were talking about local hostnames. Anyway I think my PR does what it's supposed to do
