### ISSUE TITLE
Getting TypeError for a particular URL

### ISSUE THREAD

**Issue by rahul-desai3** [sindresorhus/pageres#209]
Pageres is unable to generate snapshot for this page: http://clinclairfire.org/helpfullinks.html

It is throwing the following error:
```
'TypeError: \'undefined\' is not an object (evaluating \'trace.file\')\n→ /Users/rahul/pageres/screenshot-checker/node_modules/pageres/node_modules/screenshot-stream/stream.js on line 10 in function formatTrace'
```
I am not able to catch this error in the error callback.

How do I resolve this?

**Comment by SamVerschueren** [comment]
I'm not getting this error, but it just hangs and does nothing here.

**Comment by luizbills** [comment]
+1

**Comment by sindresorhus** [comment]
Can you try upgrading to the latest version and see if it's still an issue?

**Comment by SamVerschueren** [comment]
Tested it with `pageres-cli@3.0.0` and it works.
