### ISSUE TITLE
Use async functions in the module code and tests

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pageres#213]
Re: https://github.com/sindresorhus/pageres/pull/212/files#r41089180

-

@kevva @SamVerschueren Comment here before doing it so we don't have any conflict ;)

**Comment by SamVerschueren** [comment]
I can do this one together with https://github.com/sindresorhus/pageres/issues/186 if you like. Although `nyc` doesn't appear to work with `AVA` on my computer :).

**Comment by sindresorhus** [comment]
Cool. Actually, would be cool to use async function in the code too. What do you think?

**Comment by SamVerschueren** [comment]
Using await/async in the module would be very cool!

**Comment by sindresorhus** [comment]
:+1:

**Comment by kevva** [comment]
+11

**Comment by SamVerschueren** [comment]
Implementing this.

**Comment by SamVerschueren** [comment]
It looks like I can't use async/await if the test function has to wait for stream data like this method. https://github.com/sindresorhus/pageres/blob/master/test/test.js#L45-L58

```js
test('generate screenshots', async t => {
	const streams = await new Pageres()
		.src('yeoman.io', ['480x320', '1024x768', 'iphone 5s'])
		.src('todomvc.com', ['1280x1024', '1920x1080'])
		.run();

	t.is(streams.length, 5);
        streams[0].once('data', data => t.true(data.length > 1000));
});
```

The test that checks for data.length is not executed. Using `t.plan` or `t.end` doesn't work as an async/await test will stop immediately at the end of the function.

If you guys know another solution for this, that would be nice. If not, I will create an `event-pify` library that can be used like this.

```js
test('generate screenshots', async t => {
	const streams = await new Pageres()
		.src('yeoman.io', ['480x320', '1024x768', 'iphone 5s'])
		.src('todomvc.com', ['1280x1024', '1920x1080'])
		.run();

	t.is(streams.length, 5);

	const data = pify(streams[0], 'data', Promise);

	t.true(data.length > 1000);
});
```

`event-pify` is probably something you would only use in tests I guess.

Any insights or improvements are more then welcome!

**Comment by sindresorhus** [comment]
You can just do this:

`pify(streams[0].once, Promise)('data');`

Might need to do this, not sure:

`pify(streams[0].once.bind(stream[0]), Promise)('data');`

**Comment by SamVerschueren** [comment]
Awesome! Thanks for pointing this out :).

**Comment by SamVerschueren** [comment]
Oh yes, yesterday I thought I could use `pify` as well. But the thing is that the first argument of the `once` method is not an error object but the actual data object. By using pify, it would reject the promise with the data object as error.

So maybe we should create a `no-error-pify` or something. Or add an option to the current `pify` module. But don't like spoiling such a nice module with something like this :).

Any ideas?

**Comment by sindresorhus** [comment]
Ah, good point.

Could always use `t.plan`:

```js
test('generate screenshots', async t => {
	t.plan(2);

	const streams = await new Pageres()
		.src('yeoman.io', ['480x320', '1024x768', 'iphone 5s'])
		.src('todomvc.com', ['1280x1024', '1920x1080'])
		.run();

	t.is(streams.length, 5);
        streams[0].once('data', data => t.true(data.length > 1000));
});
```

**Comment by SamVerschueren** [comment]
`t.plan` doesn't work. If I use `t.plan(2)` in the example above, it will throw an error

```
 Assertion count does not match planned
```

If I use `t.plan(1)`, it works but it will only test for the length of the streams, not the data itself.

**Comment by sindresorhus** [comment]
> t.plan doesn't work. If I use t.plan(2) in the example above, it will throw an error

Sounds like a AVA bug. `t.plan()` should work in async functions too. Mind opening a ticket?

-

I guess `pify-event` or something might make sense here then.

**Comment by SamVerschueren** [comment]
Will open a ticket. In the meantime, will create a `pify-event` module.

**Comment by SamVerschueren** [comment]
So I created [rfpify](https://github.com/samverschueren/rfpify) and it works for `.once` like this

```js
const data = await rfpify(streams[0].once.bind(streams[0]), Promise)('data');
```

But it looks quite ugly when I have to use `pipe`.

```js
await rfpify(streams[0].pipe.bind(streams[0]))(concatStream(data => {
	const size = imageSize(data);
	t.is(size.width, 1024);
	t.is(size.height, 768);
}));
```

**Comment by SamVerschueren** [comment]
I found [concat-stream-promise](https://www.npmjs.com/package/concat-stream-promise) which seems to work very well.

Downsides:
- Not used a lot
- No tests

```js
test('support local relative files', async t => {
	const streams = await new Pageres().src('fixture.html', ['1024x768']).run();

	t.is(streams[0].filename, 'fixture.html-1024x768.png');

	const data = await streams[0].pipe(concatStream());

	t.true(data.length > 1000);
});
```

**Comment by sindresorhus** [comment]
Just `pify` the normal concat-stream. I'm not a fan of useless promise wrappers.

**Comment by SamVerschueren** [comment]
I tried to `pify` the `concat-stream` library but it didn't seem to work. Will have a look at it again.

**Comment by sindresorhus** [comment]
Ok, I made a simple module for this: https://github.com/sindresorhus/get-stream

**Comment by SamVerschueren** [comment]
You Sindre... are amazing ;)! Thanks for the module!

One tiny question. Dropping node 0.10 support in your current modules, or only this one? I see you aren't using `pinkie-promise`. Probably to keep it as minimal as possible.

**Comment by sindresorhus** [comment]
Still supporting Node 0.10 here. We can just do `global.Promise = pinkiePromise` at the top of the test file. And yes, did it to stay minimal.

**Comment by SamVerschueren** [comment]
Was just wondering because `travis` isn't running on `0.10`.

But thanks again for the module!

**Comment by sindresorhus** [comment]
Oh, yeah, then we don't have to do that.

**Comment by SamVerschueren** [comment]
Still have to find a way to `pify` the pipe and `concatStream` stuff.

```js
const data = await streams[0].pipe(rfpify(concatStream.bind(concatStream), Promise)());
```

Restults in `Promise rejected → TypeError: dest.on is not a function`

**Comment by sindresorhus** [comment]
Why not use `get-stream` there? Can you submit the pull request and we can discuss inline? Will also make it easier for me to suggest solutions.

**Comment by kevva** [comment]
Fixed by https://github.com/sindresorhus/pageres/commit/2acdad9ece48e88fac2624e2c575274e4b475039 and https://github.com/sindresorhus/pageres/commit/38f88d85e59400f9b36a76642d7bf53f6b1dcc07.
