### ISSUE TITLE
Upgrade pageres-cli to pageres@3 and ES2015ify the tests

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pageres#216]
...and https://github.com/sindresorhus/grunt-pageres

@kevva @arthurvr @SamVerschueren Any takers? :v:

**Comment by SamVerschueren** [comment]
Will do it :).

**Comment by sindresorhus** [comment]
:sparkles:  :+1: :sparkles:

**Comment by SamVerschueren** [comment]
@sindresorhus wondering why `meow` isn't used in `pageres-cli`?

**Comment by sindresorhus** [comment]
Just haven't gotten around to it.

**Comment by SamVerschueren** [comment]
No problem, good to know :).

**Comment by kevva** [comment]
https://github.com/sindresorhus/grunt-pageres/pull/4

**Comment by SamVerschueren** [comment]
I have issues running the tests of `pageres-cli` with the latest AVA (0.3.0). The only two tests executed  are

- remove temporary files on cancel
- generate screenshots from a list of screen resolutions

Any ideas?

**Comment by sindresorhus** [comment]
Might be related to https://github.com/sindresorhus/pageres/issues/186#issuecomment-151286259 I have a feeling we have a race bug or some kind of thing that makes it fail in pageres.

**Comment by SamVerschueren** [comment]
Ok, will try to have a look into it this evening. Not that familiar with the AVA internals though. So if you have any idea where I should start looking, feel free to share :).

**Comment by sindresorhus** [comment]
You could try making the tests `test(` → `test.serial(` to see if it's a race issue of some kind.

**Comment by SamVerschueren** [comment]
That's not it. Tried to run only one test (the first one) and even then it does not complete.

**Comment by sindresorhus** [comment]
No, I meant in `pageres`, not `pageres-cli`. There's clearly something weird going on there that might be the cause of this too.

**Comment by SamVerschueren** [comment]
Both `pageres-cli` and `grunt-pageres` are bumped to `3.0.1`.

**Comment by sindresorhus** [comment]
:v:
