### ISSUE TITLE
being able to trigger a configurable click

### ISSUE THREAD

**Issue by maboiteaspam** [sindresorhus/pageres#218]
Hi!

First, i wanted to post on grunt-pageres rather than pageres-cli.

I m missing an option to trigger a configured click as phantomjs expect it, http://stackoverflow.com/a/16803781

Sure i could rewrite the code to specifically support phantomjs ... but yeah, sounds like to me, it could be handled by the underlying program, pageres.

how do you think about it ? Have you faced such case too ? Did you solved it differently ?

**Comment by SamVerschueren** [comment]
So what you want is an option to click on an element before the screen is captured?

**Comment by maboiteaspam** [comment]
yes, i _miss_ such option.

**Comment by sindresorhus** [comment]
That's too specific, but I'm open to an option that accepts some JS run in the page context. You could then do anything.

**Comment by maboiteaspam** [comment]
got it, thanks!

**Comment by kevva** [comment]
Guess that would've to be added in `screenshot-stream`.

**Comment by maboiteaspam** [comment]
Hi !,

this is all done, up and running. except i won t fight to merge into main.

so for other users which would like to enjoy such feature, 
you can run `npm i mabaoiteaspam/grunt-pageres`. 

That will __require__ git, so its not production friendly.
But yeah, you can go with it.

Then, if one want to merge into main, that s cool too.

Thanks again for the script idea!
Great coding, that was really friendly to update, besides all those es6, babel, ava, xo which gave me some pain as i m new user to it.

have fun !

**Comment by IonicaBizau** [comment]
@sindresorhus @maboiteaspam Is this now possible? At least running some JavaScript code on the page before taking the screenshot?

**Comment by sindresorhus** [comment]
@IonicaBizau Nope. Not sure why this was closed. I opened a new issue: https://github.com/sindresorhus/pageres/issues/281
