### ISSUE TITLE
change timeout 

### ISSUE THREAD

**Issue by wanglong167** [sindresorhus/pageres#221]
Set the timeout 10 seconds

**Comment by SamVerschueren** [comment]
Why? If you want that, just provide it in the options.

**Comment by wanglong167** [comment]
Don't want to open a Web site for more than 10 seconds

Waste of server

**Comment by SamVerschueren** [comment]
I mean the `delay` option of pageres.

It's possible that I don't understand your question entirely, so please elaborate :)! Why?
