### ISSUE TITLE
Add an option for custom CSS

### ISSUE THREAD

**Issue by Djiit** [sindresorhus/pageres#228]
It would be great to have an option to allow custom CSS to be applied on the webpage by phantomJS before rendering the screenshot. Do you plan to add this feature in the future ?

Thx

**Comment by kevva** [comment]
We might as well expose the whole `page` object itself and let the user do whatever. Thoughts @sindresorhus?

**Comment by sindresorhus** [comment]
@kevva :-1: Then the user is free to change and break anything and will complain to us when it breaks what we do. I'd rather have defined and controlled ways to do this.

**Comment by kevva** [comment]
That's the downside of the flexibility that'd give, yeah. I'll add an option for this then.

**Comment by SamVerschueren** [comment]
How should the API look like for this feature? Would it accept raw css, or a file?

```js
const pageres = new Pageres({delay: 2})
    .src('yeoman.io', ['480x320', '1024x768', 'iphone 5s'], {crop: true})
    .css('custom.css')
    .dest(__dirname)
    .run()
    .then(() => console.log('done'));
```

**Comment by Djiit** [comment]
FWIW, the raw css options would be suficient for my personal intended use.

**Comment by SamVerschueren** [comment]
Actually, it would be pretty easy to check if the argument provided is a file or not so we can support both. I can imagine that if you really want to add a lot of custom css stuff, you would rather prefer a separate file instead of embedding the css.

**Comment by Djiit** [comment]
I really appreciate the effort guys. Thanks a lot !
