### ISSUE TITLE
CLI: wrap URL in double quotes

### ISSUE THREAD

**Issue by hurricaneditka16** [sindresorhus/pageres#235]
CLI doesn't like URLs with &. Wrapping with double quotes solved the issue. Maybe it's just Windows. Thought this may help.

![pageres](https://cloud.githubusercontent.com/assets/1189675/12906757/6f55c5fe-ceb1-11e5-9db3-1baa16318583.PNG)

**Comment by sindresorhus** [comment]
That has nothing to do with Pageres. You always have to quote CLI arguments if they contain shell special characters.
