### ISSUE TITLE
output file?

### ISSUE THREAD

**Issue by corysimmons** [sindresorhus/pageres#238]
Is there a reason there is no output file option?

I saw https://github.com/sindresorhus/pageres/issues/23 but it really doesn't explain it.

Willing to accept PRs on it?

**Comment by SamVerschueren** [comment]
Do you mean the filename option?

**Comment by corysimmons** [comment]
derp

**Comment by corysimmons** [comment]
out of curiosity, would there be any way to set a random string on the filename so it doesn't overwrite?

**Comment by sindresorhus** [comment]
Yes, that would be a good feature request. Open a new issue. When a file exists, append something random to the filename and try again.
