### ISSUE TITLE
‼ Specify a url

### ISSUE THREAD

**Issue by xosan4ever** [sindresorhus/pageres#240]
Hi!
When I start 'pageres 640x768 < urls.txt' i see ‼ Specify a url
urls.txt like:
site.ru
site1.ru
...
line ending LF
Win10x64
What I do wrong?

thanks to answer.

**Comment by sindresorhus** [comment]
Pageres no longer reads from stdin: https://github.com/sindresorhus/pageres-cli/releases/tag/v2.0.0 See new instructions: https://github.com/sindresorhus/pageres-cli#google-analytics-screen-resolutions

-

Please make a better effort next time when posting an issue.
