### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by glenn9** [sindresorhus/pageres#243]
Hi, is there a way to wait for a JS callback function before taking the screenshot? Delay is a dirty alternative and can fail if the page has lots of images or if the connection of the server is slow

**Comment by SamVerschueren** [comment]
As far as I know it should wait untill the page is fully loaded. From the `PhantomJS` docs regarding [page.open()](http://phantomjs.org/api/webpage/method/open.html):

> Opens the url and loads it to the page. Once the page is loaded, the optional callback is called using `page.onLoadFinished`, and also provides the page status to the function ('success' or 'fail').

So if this is not working correctly, I guess it's a PhantomJS issue rather then a pageres issue.
