### ISSUE TITLE
`es5-shim` dependency is not needed any more

### ISSUE THREAD

**Issue by Arkni** [sindresorhus/pageres#247]
Introduced in d297edc1e8960661c65215d0f2b66f366d960e1e, because of `PhantomJS` 1.9.x lacks `Function.prototype.bind`. But this is not needed any more as the current code use `PhantomJS 2.x.x` which support that method.

**Comment by SamVerschueren** [comment]
It isn't used anymore though, but good catch :)! It was removed from pageres and extracted to [screenshot-stream](https://github.com/kevva/screenshot-stream). It was removed from `screenshot-stream` a while ago as per [this commit](https://github.com/kevva/screenshot-stream/commit/bc8bf1429ae111f2c904da14ec5248e251a6f62a).

**Comment by Arkni** [comment]
Ah, thanks for the explanation :)
