### ISSUE TITLE
get output .getComputedStyle(document.body) from CLI

### ISSUE THREAD

**Issue by nvcken** [sindresorhus/pageres#248]
somes URL sites get this error

**Comment by SamVerschueren** [comment]
What error? Can you show use the stacktrace with a copy-paste or print-screen?

**Comment by nvcken** [comment]
Sorry, I get only that output after run cli, likes this
```
$ pageres genk.vn  320x568 # 3 screenshots
.getComputedStyle(document.body)
```

**Comment by SamVerschueren** [comment]
Thanks for the info. Will have a look at it when I find the time.

**Comment by SamVerschueren** [comment]
It seems that hose urls can't be opened by phantomjs. the [page.open](https://github.com/kevva/screenshot-stream/blob/master/stream.js#L53-L57) returns the status `fail` for those resources. So I don't think we can do something about it to be honest and is rather a phantomjs issue.

**Comment by nvcken** [comment]
ok, it make sense. Thanks @SamVerschueren
