### ISSUE TITLE
Multiple "dynamic" urls?

### ISSUE THREAD

**Issue by romanlelek** [sindresorhus/pageres#249]
Hello, 

I am generating various count of html files to my dist folder, which I want to screenshot. Is it possible to pass pageres in urls parameter something like dist/*.html. (E.g. Make screenshots for all files ending with .html?)

I am using Grunt, passing local path and I have tried this:
    screenshot: {
        options: {
            urls: ['<%= paths.dist %>/*.html'],
            sizes: ['iPhone', '800x600'],
            dest: '<%= paths.dist %>/screenshots'
        }

Thank you. 
Best regards
Roman

**Comment by sindresorhus** [comment]
Not natively. The main focus are URLs. However, you can easily just use [`globby`](https://github.com/sindresorhus/globby) and iterate over the results, creating a config, and then passing it to Grunt. It's just JavaScript after all.
