### ISSUE TITLE
Add timeout

### ISSUE THREAD

**Issue by nikhil32** [sindresorhus/pageres#250]
I am using this library. But I didn't find an option to set the time out. My use case is simple, set a time out and if my target website is not loaded with the time, stop processing or throw an error. Is there a way?

**Comment by SamVerschueren** [comment]
`pageres` is about taking screenshots of websites, not about testing the load time, there are other tools for that. Not a use case we should support imo.

**Comment by sindresorhus** [comment]
I think it makes sense to set some kind of timeout, but I don't see the point in making it configurable. We can maybe set it to 60 sec or something.

http://stackoverflow.com/questions/16854788/phantomjs-webpage-timeout
http://phantomjs.org/api/webpage/property/settings.html

**Comment by kevva** [comment]
Landed in https://github.com/kevva/screenshot-stream/commit/ea2dda24dc9992de98984fc876cada94ab6a167d :fireworks:.

**Comment by sindresorhus** [comment]
@nikhil32 Just reinstall Pageres to get it.

**Comment by nikhil32** [comment]
Thanks everyone...
