### ISSUE TITLE
Getting blank images

### ISSUE THREAD

**Issue by nikhil32** [sindresorhus/pageres#253]
Hi,

For certain URLs, we are getting a black(/empty/blank) of the size requested with file size of 16.7KB. This is happening intermittently  for these urls

http://www.iciciprulife.com/public/plans.htm
http://www.iciciprulife.com/public/default.htm

Any idea on why this is happening, thanks in advance.

**Comment by kevva** [comment]
Can't reproduce this using `4.1.1`. What version are you using? I noticed that the pages took some time to load in the browser so maybe you should try using the `delay` option?

**Comment by SamVerschueren** [comment]
Can't reproduce either with `pageres-cli@3.1.0`.

**Comment by nikhil32** [comment]
@kevva it's not happening consistently but intermittently. I am getting some blank image with same pixels I requested. for reference the image is http://cdn25.vizury.com/demo/ssp/IN_urbanladder_May13/notification/00a33f81-7d1f-4aeb-b896-7a12bb2e238d.jpg

**Comment by SamVerschueren** [comment]
@nikhil32 Can you provide us with some more information?

1. Are you using `pageres` or `pageres-cli`?
2. What version of `pageres`/`pageres-cli` are you using? Are you using the latest version?
3. Have you tried using the `delay` option?

**Comment by nikhil32** [comment]
I am using pageres 4.1.0.  I haven't tried with delay option.

**Comment by nikhil32** [comment]
I am trying now with delay option and we will see for one day if we are getting that blank image again. If not we will close the issue. Thanks for your responses

**Comment by kevva** [comment]
@nikhil32, did you experience this issue again?

**Comment by nikhil32** [comment]
So far we didn't get the error. So closing the issue. If I am facing it again, will update.

**Comment by kevva** [comment]
:+1:
