### ISSUE TITLE
Support for data URIs

### ISSUE THREAD

**Issue by JacksonGariety** [sindresorhus/pageres#254]
When using a data URI as a pageres source (`data:text/html;base64,PGgxPkZPTzwvaDE+`), pageres generates a white, empty image file.

Is it possible to get pageres to use data URIs? phatom has support for data uris afaik!

**Comment by sindresorhus** [comment]
Probably just need to support data-URLs in our URL detection: https://github.com/sindresorhus/pageres-cli/blob/4301a0964f5e6f352299c44b4ad3f1d38d2c8db4/cli.js#L150

PR welcome :)
