### ISSUE TITLE
Support for passing proxy information

### ISSUE THREAD

**Issue by yasirhusain** [sindresorhus/pageres#260]
Hi,

In your tool I could not find any option to pass Proxy information. Currently, we use the options available in phantomjs but could not find any parameter information for PAGERES.

phantomjs --proxy=<value> --proxy-type=<value> --proxy-auth=<value> URL FILENAME.jpg

If it is available can you please provide me link to your user guide or if not, then when can we expect this option to be available.

TIA.

**Comment by sindresorhus** [comment]
There's no support and not really interested in adding more options, sorry.
