### ISSUE TITLE
Add pixel ratio option

### ISSUE THREAD

**Issue by HugoGresse** [sindresorhus/pageres#263]
I'm searching for a way to change the pixel ratio of the page so a 1080px width on a DPR of 2 will look like a 384 width on the webview. 

I didn't see any option for this :/

**Comment by HugoGresse** [comment]
I will be really great to have this feature as NO other cli has it currently. For me it's a required feature to use Pageres :/

**Comment by kevva** [comment]
This is currently not possible using PhantomJS. See https://github.com/ariya/phantomjs/issues/10964.

**Comment by HugoGresse** [comment]
There are some hack like this project https://github.com/DeviaVir/pixelratio-screenshots

**Comment by kevva** [comment]
I rather wait for this to get implemented in PhantomJS than using workarounds like that :).

**Comment by SamVerschueren** [comment]
> I rather wait for this to get implemented in PhantomJS

Probably never ;). When Headless Chrome is released, we will switch to that one and ditch PhantomJS.

**Comment by HugoGresse** [comment]
well, Headless chrome is 5 bugs away, in the meantime did you consider switching to Electron?

cf Headless chrome : https://bugs.chromium.org/p/chromium/issues/detail?id=546953#c54
cf Electron over PhantomJS : https://github.com/juliangruber/url-to-screenshot/issues/12

**Comment by sindresorhus** [comment]
We've considered Electron, but it requires a lot of setup to work headlessly in Linux (which is the main target), so we would rather wait on Chrome than having to go through all that.

**Comment by kevva** [comment]
> Probably never ;).

Huh, 2.0 only took a couple of years.

**Comment by HugoGresse** [comment]
any progress to work with Headless chrome as it was released?

**Comment by kevva** [comment]
Yes, I've created https://github.com/kevva/chromium-bin but it's not working due to the `bin-wrapper` module having problems extracting it correctly. I'm still working on improving `bin-wrapper` but I hope to be finished with it soon.

**Comment by sindresorhus** [comment]
In v5 (which uses Puppeteer), you can use the `scale` option for this.
