### ISSUE TITLE
null is not an object (evaluating 'clipRect.height')

### ISSUE THREAD

**Issue by oeon** [sindresorhus/pageres#265]
Hello,

I'm running pageres-cli 3.1.0 like so, on an element that is 698x5221:
`pageres localhost:3000/apps/9ce6122d-f3b1-4a91-8741-2b1ca7c4d312/edit --selector='div#form.form-builder.builder'`

and getting a message:
`PHANTOM ERROR: TypeError: null is not an object (evaluating 'clipRect.height') → phantomjs://code/stream.js on line 111`

I've tried to `npm uninstall` phantomjs and install through homebrew and reinstall.
Any ideas what the problem may be? Thank you!

**Comment by kevva** [comment]
Is the page hosted somewhere?

**Comment by oeon** [comment]
No, I'm sorry @kevva I only have a local instance to test upon.

**Comment by SamVerschueren** [comment]
Is it possible to host it somewhere, either via a gist or plunkr or whatever? Or is this private/corporate code?

**Comment by oeon** [comment]
Yes, @SamVerschueren I should have added that detail...it is code from a private repository.

**Comment by kevva** [comment]
Are you sure that your selector is correct?

**Comment by oeon** [comment]
It works! My apologies, as I think this was my own issue...my app uses HTTP Auth and after setting that _with_ the Cookie option flag, it is working as expected. Thank you for this great tool.
