### ISSUE TITLE
The whole process fails if there is an issue with separate sshot capture in the list of URLs. 

### ISSUE THREAD

**Issue by slotix** [sindresorhus/pageres#270]
Thank you for awsome lib. 
I'm using pageres client

Here are some examples:

`pageres http://acu.yuku.com` - Ok
`pageres http://adrenaline.uol.com.br/forum` - Failed
`pageres http://acu.yuku.com http://adrenaline.uol.com.br/forum`  - Failed 

Why http://acu.yuku.com is not processed in the last case even everything is ok if it passed separately?

**Comment by Upguard** [comment]
I'm also having similar issues with taking screenshots of sub-pages on a website.

**Comment by sindresorhus** [comment]
Yeah, I agree it should continue even though some URLs failed. For now you can simply do a shell script loop with pageres instead of using multiple arguments. Help welcome for fixing it.
