### ISSUE TITLE
Parallax printscreens

### ISSUE THREAD

**Issue by JensDebergh** [sindresorhus/pageres#272]
I'm trying out pageres on several responsive websites. The problem I'm experiencing is when loading parallex pages.

How do I get a proper parallax view of the website and not the first slide?

Website: http://scrooser.com/en/home/

Kind regards

![desktop](https://cloud.githubusercontent.com/assets/6651506/18511340/7479a54a-7a83-11e6-9269-0b5961390271.png)

**Comment by borislemke** [comment]
from the screenshot it seems to be an issue with the website itself and not pageres. you're probably using height:100vh on the first slider, correct? if this is the case, you should set a max-height in pixel unit as well!

**Comment by SamVerschueren** [comment]
Try what @borislemke said. You could try overwriting the css with the [css](https://github.com/sindresorhus/pageres#css) property. The first screen just stretches until it fills the entire viewport which in case of PhantomJS is the entire screenshot.

**Comment by SamVerschueren** [comment]
Okay, gave it a go myself and it works.

```
$ pageres http://scrooser.com/en/home/ --css='.page-home #start-section { max-height: 900px; }'
```

Thanks @borislemke for the tip!
