### ISSUE TITLE
phantomjs binary not executing on AWS lambda

### ISSUE THREAD

**Issue by zeroasterisk** [sindresorhus/pageres#275]
Have you gotten this working on AWS lambda?

I was thinking that would be a very cool isolated, custom, scaleable, cheap microservice.

I've got the basics working, testing locally... but when executing on AWS lambda I get:

```
Error: /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: cannot execute binary file
```

I assume this is a file permissions error after copy.

Just wondering if you've run into it before.

**Comment by SamVerschueren** [comment]
Yes I managed to get it working on AWS Lambda. But in order to make it work, you have to be sure to build your zip file (`npm install` + zip) on a linux machine. It will not work if you build it on macOs or Windows because the binary is OS specific.

**Comment by zeroasterisk** [comment]
Yup - I was leaning that direction.

Here's a janky, but functional quick-fix, run `npm i` from inside a docker container:
https://gist.github.com/zeroasterisk/ad72b6737623d85be28f5ce23e755b90

**Comment by SamVerschueren** [comment]
> run npm i from inside a docker container:

Yes, that should do the trick as well :). In my case, I let Jenkins build and deploy my artifact which runs linux. So that's also a solid option.

**Comment by deanmraz** [comment]
@zeroasterisk have you had any memory issues with using lambda? I've tried other js solutions and ran into memory limits.

**Comment by zeroasterisk** [comment]
Not that I've noticed... I maxed out the RAM and time limits on the lambda when setting it up

**Comment by skylarmb** [comment]
I am getting this error when manually calling the linux binary using `execFile`. The binary is supposedly the correct one for the lambda environment (Amazon Linux) as I `npm install`ed on an Amazon Linux ec2 instance, verified the binary works there, and then lifted the binary into my repo, but the issue persists. I will update this when I find the solution for future google surfers.

**Comment by xxdannilinxx** [comment]
The pdf generator packages are deprecated and don't work on aws lambdas, just this new package I found.

https://www.npmjs.com/package/html-pdf-lambda
