### ISSUE TITLE
Screenshot multiple elements with the same selector.

### ISSUE THREAD

**Issue by nickcolley** [sindresorhus/pageres#276]
If I have a selector say '.button' and there's multiple on the page it'll only capture the first.

Any idea if there's scope to capture each instance?

**Comment by sindresorhus** [comment]
We intentionally don't support that to keep it simple. You could maybe run `pageres` multiple times and use the CSS `:nth-child()` pseudo-selector with an increasing number. Not something we're interested in having though.

**Comment by nickcolley** [comment]
Thanks 👍
