### ISSUE TITLE
Run some custom JS code before capturing the screenshot

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pageres#281]
From #218. We've gotten requests for that multiple times. I'm thinking a `script` option.

PR welcome.

**Comment by IonicaBizau** [comment]
@sindresorhus Where is the `css` option interpreted currently? I took a quick look at the code but I couldn't find it.

**Comment by sindresorhus** [comment]
I should have mentioned. Everything is passed to `screenshot-stream` and handled here: https://github.com/kevva/screenshot-stream/blob/master/stream.js

**Comment by IonicaBizau** [comment]
@sindresorhus Thanks! I'm trying to figure out where the `screenshot-stream` is used in this module... because I cannot find it. Can you please guide me? :grin:

**Comment by kevva** [comment]
https://github.com/sindresorhus/pageres/blob/master/lib/util.js#L108

**Comment by IonicaBizau** [comment]
@kevva Thanks! :cake:

**Comment by kevva** [comment]
https://github.com/kevva/screenshot-stream/pull/36

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/screenshot-stream/commit/7902dbc53f8d67b031eeacab675e9c8c625429a0.
