### ISSUE TITLE
Disable JavaScript in the phantomjs instance

### ISSUE THREAD

**Issue by ababushkin** [sindresorhus/pageres#285]
Hi there,

Is there a way to disable JavaScript on the page where the screenshot is being captured?

Cheers - Anton

**Comment by sindresorhus** [comment]
Doesn't seem like it's possible, no: http://stackoverflow.com/a/30693757/64949

**Comment by nsisodiya** [comment]
@sindresorhus - we need to take a screenshot with disabling JavaScript to check server-rendered pages. How to do this. there must be some options or some way.
