### ISSUE TITLE
"script" option doesn't work?

### ISSUE THREAD

**Issue by nabarabane** [sindresorhus/pageres#289]
Hello, I need to modify DOM before capturing screenshot.
Can you explain how "script" option really works? Is it suitable for such cases? Maybe you show some example?

I tried this code for test:
```js
var pageres = new Pageres({
  delay: 2,
  script: "alert('Alert!')"
})
  .src("site", ["1200x1200"], {crop: true, filename: "cover"});
```
And I get no result, just usual page screenshot without alert box. Am I doing something wrong? Or this option doesn't work?

**Comment by SamVerschueren** [comment]
It should work though. Try something like this instead.

```document.getElementsByTagName('body')[0].style.backgroundColor = 'red';`

**Comment by nabarabane** [comment]
I didn't try that at first. Thank you, it works. Providing filename works too. Awesome feature.

**Comment by guilhermefalcao** [comment]
Guys I'm trying to use `window.scrollTo(0, 1000);` before capturing screenshot. But for some reason it doesn't work. 

Here is a piece of my code:
`const pageres = new Pageres({
            delay: 10,
            css: '.navFloater.navbar.navbar-static-top.bs-docs-nav, .navbar-brand.yocale-logo-header, nav.navbar-collapse.bs-navbar-collapse.collapse.y-nav-white{display: none !important}',
            script: "window.scrollTo(0, 1000);"
          })`

Sorry if it is a dumb question, I'm new on javascript.
Thank you

**Comment by SamVerschueren** [comment]
Pageres takes a screenshot of your entire page, so `window.scrollTo` doesn't do anything because it can't scroll. Or am I missing something?
