### ISSUE TITLE
npm install Pageres - keeps trying and failing at phantomjs-1.9.2 download

### ISSUE THREAD

**Issue by chaddbennett** [sindresorhus/pageres#290]
PhantomJS detected, but wrong version 1.9.0 @ /usr/bin/phantomjs.
Downloading http://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.2-linux-x86_64.tar.bz2
Receiving...
Error requesting archive
Phantom installation failed [Error: Error with http request: { 'content-type': 'text/html; charset=UTF-8',
  'content-length': '1603',
  date: 'Mon, 09 Jan 2017 17:12:08 GMT',
  connection: 'close' }] Error: Error with http request: { 'content-type': 'text/html; charset=UTF-8',
  'content-length': '1603',
  date: 'Mon, 09 Jan 2017 17:12:08 GMT',
  connection: 'close' }

**Comment by sindresorhus** [comment]
This is the place to open issue about the PhantomJS binary install problems: https://github.com/Medium/phantomjs/issues

**Comment by chaddbennett** [comment]
ok thanks!
