### ISSUE TITLE
Css calc() not rendering

### ISSUE THREAD

**Issue by Jack89ita** [sindresorhus/pageres#292]
Hello!
I was trying pageres I find it very usefull, but there is a problem with the block that have some "calc()" instruction in css: they are not rendered.
Anyone got the same problem?Any fix?
Thank you very much

**Comment by SamVerschueren** [comment]
From https://github.com/ariya/phantomjs/pull/13081/files, try to use `-webkit-calc(100% - 48px);`.

If it doesn't work we're very sorry but it's a PhantomJS issue that we can't solve. We hope to be able to switch this to headless chrome, but up until now we're stuck with PhantomJS. Let us know if it fixed your issue.

**Comment by Jack89ita** [comment]
Thank you for the answer, but unfortunatly -webkit-calc(100% - 48px); is not working...
Don't know how to fix that, i hope one day they will fix that bug..

**Comment by Jack89ita** [comment]
Hi! following the phantom js github page they told me to try to use the new beta version ad see if the problem persists.
Here is the link:
"Please try 2.5.0-beta from [https://bitbucket.org/ariya/phantomjs/downloads/]"
Can we try with this version?
Thank you.
