### ISSUE TITLE
Problem to execute examples

### ISSUE THREAD

**Issue by victorferraz** [sindresorhus/pageres#293]
When I try to execute this example 
```
const pageres = new Pageres({delay: 15})
   .src('yeoman.io', ['480x320', '1024x768', 'iphone 5s'], {crop: true})
    .src('todomvc.com', ['1280x1024', '1920x1080'])
    .src('data:text/html;base64,PGgxPkZPTzwvaDE+', ['1024x768'])
    .dest(__dirname)
    .on('warning', err => console.log(err))
    .run()
    .then(() => `console.log('done'));
```

Console shows for me these errors:

Unable to load resource #4 (Operation canceled) → http://todomvc.com/site-assets/main.min.js
Unable to load resource #66 (Operation canceled) → https://apis.google.com/js/plusone.js
Unable to load resource #34 (Operation canceled) → https://gravatar.com/avatar/2ad7eb39d40ec50b8a16f0924a664ad2?s=144
Unable to load resource #34 (Operation canceled) → https://gravatar.com/avatar/2ad7eb39d40ec50b8a16f0924a664ad2?s=144
Unable to load resource #30 (Operation canceled) → https://gravatar.com/avatar/6d95827ad2de5f374947b02983d4c85b?s=144

My node version is: 6.0.0
Thanks

**Comment by SamVerschueren** [comment]
Not sure why this happens. It works perfectly fine here. Are you using the latest version in a fresh project?

**Comment by victorferraz** [comment]
Hmm, I tried again using network cable and it  worked, but the problem is related with my network, but anyway I found a thread about that:
https://github.com/ariya/phantomjs/issues/12750
I will close this issue, thanks @SamVerschueren  :)
