### ISSUE TITLE
pageres cli delay bug

### ISSUE THREAD

**Issue by clement360** [sindresorhus/pageres#294]
the cli crashes overtime I try and delay the capture using the cli:
![image](https://cloud.githubusercontent.com/assets/2770596/22952591/334d8500-f2d3-11e6-8bed-770a2d07e9fe.png)

also the cli and npm module both seem unable to capture pages that rely heavily on polymer:
like [google maps polymer element](https://elements.polymer-project.org/elements/google-map\?view\=demo:demo/polys.html\&active\=google-map)

**Comment by SamVerschueren** [comment]
We use PhantomJS in the background which probably can't render Polymer. Not sure about the bug, but probably related. We are waiting for headless chrome so we can ditch PhantomJS. So I don't think we can do much about this.
