### ISSUE TITLE
URL hash discarded for single page applications

### ISSUE THREAD

**Issue by wopian** [sindresorhus/pageres#297]
[Vue](https://vuejs.org/)'s router and many other frameworks used by single page applications usally [defaults](https://router.vuejs.org/en/essentials/history-mode.html) to a hash mode - i.e it uses the URL hash to simulate a full URL.

Due to how the slugify dependency handles URLs, the `#` is stripped from the URL - leaving all the pages with identical URLs. I.e, the following all become `hb.wopian.me`:
- [`hb.wopian.me`](https://hb.wopian.me)
- [`hb.wopian.me/#/@wopian`](https://hb.wopian.me/#/@wopian)
- [`hb.wopian.me/#/anime/cowboy-bebop`](https://hb.wopian.me/#/anime/cowboy-bebop)
- [`hb.wopian.me/#/manga/20th-century-boys`](https://hb.wopian.me/#/manga/20th-century-boys)

This causes the output of pageres to only contain a single image per resolution showing whichever page was processed last.

- `hb.wopian.me-1920x1080.png`
- `hb.wopian.me-412x732.png`

Unfortunately I'm required to use the hash mode for routing as modifying nginx/apache config files is required for dynamically generated pages (e.g `hb.wopian.me/anime/...`) - something you can't do with GitHub Pages.

### Code
```js
const PageRes = require('pageres')

const pageres = new PageRes({ delay: 10 })
  .src('hb.wopian.me', [ '412x732', '1920x1080' ])
  .src('hb.wopian.me/#/@wopian', [ '412x732', '1920x1080' ])
  .src('https://hb.wopian.me/#/anime/cowboy-bebop', [ '412x732', '1920x1080' ])
  .src('https://hb.wopian.me/#/manga/20th-century-boys', [ '412x732', '1920x1080' ])
  .dest(`${__dirname}/../screenshot`)
  .run()
  .then(() => console.log('done'))
```

---

Edit: PhantomJS 2.5.0-development is required to test with this site due to flex usage.

**Comment by sindresorhus** [comment]
I guess we could strip `#/` from the URL path in the filename method. Pull request welcome. Should come with a test.
