### ISSUE TITLE
Pageres-cli doesn't accept query parameters

### ISSUE THREAD

**Issue by atetc** [sindresorhus/pageres#300]
I am trying to render screen using `pageres-cli` and have issue with query parameters.

For line
`pageres index.html?lang=th`

I have this error:
Couldn't load url: http://index.html?lang=th

But even I tried to use full path for file, looks like `pageres-cli` ignore query parameters and run html without it.
`pageres file:///Volumes/Data/Projects/screen1/index.html?lang=th`

How to solve this situation?

**Comment by kevva** [comment]
See https://github.com/ariya/phantomjs/issues/14050.
