### ISSUE TITLE
Transparent background option

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/pageres#301]
If the background color isn't set, `pageres` will set it to `white`

It'd be nice to have an option to capture a transparent screenshot [like `electron-screenshot-service` does.](https://github.com/FWeinb/electron-screenshot-service#transparent)

Current behavior:

```sh
pageres https://raw.githubusercontent.com/alrra/browser-logos/master/src/chrome/chrome.png
```

Output: (PNG is no longer transparent)

![raw githubusercontent com alrra browser-logos master src chrome chrome png-1366x768](https://cloud.githubusercontent.com/assets/1402241/25166058/69020d74-2514-11e7-82d0-1496609a6543.png)

**Comment by sindresorhus** [comment]
Sure. Pull request welcome :)

**Comment by bfred-it** [comment]
😍
