### ISSUE TITLE
Doesn't work with my vue.js webapp

### ISSUE THREAD

**Issue by etiennea** [sindresorhus/pageres#302]
Here is the error I get 

    TypeError: undefined is not a constructor (evaluating 'q.nextTick(e,t)'

Any clues as to how I could get it to work?

**Comment by SamVerschueren** [comment]
Probably because of PhantomJS. We hope to switch to Headless chrome one day so all of this will be solved.

**Comment by etiennea** [comment]
Vue-resource 1.2.0 was causing this error, updating it removed it!
