### ISSUE TITLE
Won't render some websites properly

### ISSUE THREAD

**Issue by marcpope** [sindresorhus/pageres#308]
For example, try imaging angular.io or macrumors.com Angular is just blank. Macrumors is totally jacked up.

**Comment by kevva** [comment]
It's because PhantomJS doesn't support all ES2015 features. E.g. `angular.io` fails because of:

> ReferenceError: Can't find variable: WeakMap → https://angular.io/main.409b511ce1a2f78ae368.bundle.js on line 1

Try listening for the [`warning`](https://github.com/sindresorhus/pageres#pageresonwarning-callback) event.
