### ISSUE TITLE
Unable to pass cookies server-side to local files?

### ISSUE THREAD

**Issue by sustained** [sindresorhus/pageres#310]
So, I have some HTML file that generates stuff based on the query parameters. Pageres is requesting this local file and generating an image out of it.

Now, obviously you CAN'T pass query parameters to a local file. So then I changed it to use cookies instead. This doesn't work - the cookies don't make it through.

I know that in Chrome, file/local cookies are disabled unless you pass in the `--enable-file-cookies` flag.

I feel like this could be potentially the same problem, if not a similar one?

How do I make this work?

```ts
const Path    = require('path');
const Pageres = require('pageres');

const pageres = new Pageres({delay: 2})
	.src(Path.resolve(__dirname, 'profile_card.html'), ['360x160'], {
        crop: true,
        cookies: [
            'displayname=sustained;',
            'avatar=avatar.jpg;',
            'nationality=gb-eng;'
         ]
    })
	.dest(__dirname)
	.run()
	.then(() => console.log('done'));
```

**Comment by sustained** [comment]
The only solution I can think of right now is a web-server - then I'd be able to pass query parameters.

But that seems like nothing more than a hacky workaround.

**Comment by SamVerschueren** [comment]
The only other thing I can think off you can try is use the [script](https://github.com/sindresorhus/pageres#script) option to pass in custom JavaScript with some variables or something.
