### ISSUE TITLE
Error: Couldn't get any items

### ISSUE THREAD

**Issue by tom-dell** [sindresorhus/pageres#312]
Any clue on what this error message means?

```
Error: Couldn't get any items
    at module.exports.ret (/usr/local/lib/node_modules/pageres-cli/node_modules/viewport-list/index.js:25:9)
    at memoized (/usr/local/lib/node_modules/pageres-cli/node_modules/mem/index.js:32:18)
    at /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:203:29
    at next (native)
    at step (/usr/local/lib/node_modules/pageres-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/pageres-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/usr/local/lib/node_modules/pageres-cli/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at /usr/local/lib/node_modules/pageres-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at Pageres.viewport (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:211:5)
    at /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:165:19

```

**Comment by sindresorhus** [comment]
What was the command you ran?

**Comment by tom-dell** [comment]
It was just (not correct domain, as it happened to a few of them)
`pageres google.com`

**Comment by kevva** [comment]
You need to provide a size. See https://github.com/sindresorhus/pageres-cli#usage. Although it's weird that this error shows up since it shouldn't try fetching viewports [without keywords](https://github.com/sindresorhus/pageres/blob/master/lib/index.js#L129-L131).

**Comment by tom-dell** [comment]
Strange thing is that it works for every other domain, except for a few, should I add a size to every domain and try again?

**Comment by kevva** [comment]
Can you give me an example of a domain that doesn't work?

**Comment by tom-dell** [comment]
I have a list of a lot domains, I'm not sure which domains throw the error. I'll run it with a size and get back to you.

**Comment by tom-dell** [comment]
> Turns out, you don't https://github.com/sindresorhus/pageres-cli/blob/9c38bd79272e14653ab9b17230c98d02db850814/cli.js#L99-L101.

Hmm, back to square one.
