### ISSUE TITLE
obtain base64 data

### ISSUE THREAD

**Issue by simar88** [sindresorhus/pageres#314]
Is possibile to obtain the base64 data from the url instead of saving it as a file?
Thanks in advance,
Simone

**Comment by kevva** [comment]
`pageres.run()` returns `Promise<Array>` with  streams so you can do something like this:

```js
new Pageres()
    .src('google.com', ['1024x768'])
    .run()
    .then(streams => {
        streams[0].pipe(myWritableStream);
    });
```
