### ISSUE TITLE
issue about the script passed through before capturing the screen

### ISSUE THREAD

**Issue by mingtam** [sindresorhus/pageres#316]
Hi, 

I tried to run a script before capturing, like click a button first,

```
const pageres = new Pageres({
    delay: 2,
    script: "document.querySelector('.coreSpriteRightChevron').click();"
})
	.src('https://www.instagram.com/p/BWh3WDKh5c5/', ['1600x1200'], {crop: true})
	.dest(__dirname)
	.run()
	.then(() => console.log('done'));

```
However, it doesn't work ... Would you please kindly let me know if anything I did wrong?

**Comment by ianleeder** [comment]
I want to do the exact same thing, execute a click before screen capture, but `script` does nothing.  In fact searching the repo, script only appears in a YML file and the readme.  I think the `script` option is completely ignored.
