### ISSUE TITLE
phantomjs binary not used

### ISSUE THREAD

**Issue by jojomi** [sindresorhus/pageres#319]
I had trouble getting the package installed on Manjaro linux. Like said in the README, I downloaded `phantomjs` manually and put it in my PATH:

```
which phantomjs && phantomjs -v
/usr/local/bin/phantomjs
2.1.1
```

But after `npm install pageres-cli` it still is not used:

```
pageres test.de
The automatic install of PhantomJS seems to have failed.
Try installing it manually: http://phantomjs.org/download.html
```

What did I miss?

**Comment by ThomasChan** [comment]
+1

**Comment by kevva** [comment]
Open an issue at instead https://github.com/Medium/phantomjs which is the package we're using for downloading PhantomJS.

**Comment by jojomi** [comment]
@ThomasChan Perhaps it helps in your workflow, I have created a docker container for pageres-cli: https://hub.docker.com/r/jojomi/pageres/

**Comment by hdbhdb** [comment]
the download link in the readme still directs to the binaries for the archived phantomjs, not medium's phantomjs
