### ISSUE TITLE
browser min-with @ 600 pixels

### ISSUE THREAD

**Issue by tornography** [sindresorhus/pageres#32]
Hi,

it seems the browser is able to set the with to a minimum of 600 pixels.
So trying to check mobile views with a with of about 340 pixels is not possible. The screenshot itself is cropped to 340px but the content flows out of the screenshot.

regards
tornography

**Comment by astefanutti** [comment]
I've just pushed PR [13422](https://github.com/ariya/phantomjs/pull/13422) to PhantomJS to generally address that issue and that hopefully will get merged soon, see: https://github.com/ariya/phantomjs/issues/10619#issuecomment-123248071
