### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by jojomi** [sindresorhus/pageres#320]
Do you consider packaging pageres(-cli) in a working docker container? It would be a lot easier for me to add it to our workflow :).

**Comment by SamVerschueren** [comment]
You could easily do this yourself and publish the container to Docker Hub. We are not considering doing this.

**Comment by jojomi** [comment]
I took the time to do this: https://hub.docker.com/r/jojomi/pageres/

### Example usage

``` bash
docker run --rm --mount type=bind,source="$(pwd)/data",destination=/data jojomi/pageres-cli pageres [ wikipedia.org 800x600 1024x768 1600x900 1920x1080 ]
```
