### ISSUE TITLE
Issue with base64 encoded files larger than 32kb

### ISSUE THREAD

**Issue by avionipevaju** [sindresorhus/pageres#324]
Hello, 

I want to render a webpage using pageres. I'm passing HTML DOM encoded in base64. Here is my code: 
```javascript
 const Pageres = require('pageres');
 var mypage = 'data:text/html;base64,...';
 const pageres = new Pageres({delay:0})
  .src(mypage, ['1024x768'])
  .dest(__dirname)
  .run()
  .then(() => console.log('done'));
```

This works perfectly for some pages. But when string mypage is too large (larger than 32kb) pageres doesn't work. I get this error: 

``` 
(node:14068) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: spawn ENAMETOOLONG
```
Do you know if there is a solution for this problem? I'm using latest version of pageres 4.5.1.

Many thanks in advance!

**Comment by sindresorhus** [comment]
I'm pretty sure this is fixed in v5.

**Comment by sindresorhus** [comment]
This should work in v5.
