### ISSUE TITLE
Correct syntax for --selector and --hide

### ISSUE THREAD

**Issue by piet85** [sindresorhus/pageres#326]
Can you please give an example for the right syntax for the --selector and --hide options? In readme file there are no examples for this options. 
I'm trying to hide an ad that disappears in browser (firefox), when I delete the node below. So when I'm right, I should pass pageres the option --hide=ad_superbanner in some way, but it doesn't work (Error: Couldn't get any items). Tried several syntax, with ' ' " " <>, also tried with and without id= So can you tell me what is the correct syntax to hide this element in pageres?

`<div id="ad_superbanner">
                <div data-ad-slot="/47409804/fc_dfp_leaderboard" data-ad-size="[[800, 250], [970, 250], [728, 90], [950, 90], [960, 90], [970, 90], [970, 66]]" class="google-ad-inline text-center" style="" data-google-query-id="COu0uZb41NgCFQGLdwodJUwFxQ" id="fc_dfp_leaderboard"><div id="google_ads_iframe_/47409804/fc_dfp_leaderboard_0__container__" style="border: 0pt none; display: inline-block; width: 728px; height: 90px;"><iframe style="border: 0px none; vertical-align: bottom;" src="https://tpc.googlesyndication.com/safeframe/1-0-14/html/container.html" id="google_ads_iframe_/47409804/fc_dfp_leaderboard_0" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" data-is-safeframe="true" width="728" height="90" frameborder="0"></iframe></div></div>
    <div id="fc_dfp_leaderboard_mobile" data-ad-slot="/47409804/fc_dfp_leaderboard_mobile" data-ad-size="[[300, 50], [300,100], [320, 50], [320,100]]" class="google-ad-inline fcx-ad-mobile text-center"></div>
        </div>`

**Comment by sindresorhus** [comment]
You need to pass it any CSS Selector (Try Googling it). In your case, it should be: `--hide="#ad_superbanner"`

**Comment by piet85** [comment]
Thank you for your answer very fast answer! `-hide="#ad_superbanner"` did the job. I googled the CSS selector, but it wasn't clear to me what is the correct syntax for pageres. The pure CSS selector would have been #ad_superbanner, but that didn't work, so the quotation marks we're the solution. Thank you.
