### ISSUE TITLE
screenshot not including transform

### ISSUE THREAD

**Issue by chandrantwins** [sindresorhus/pageres#329]
My page is having this css stlye.. but its not applied in screenshot.. Please help to me solve this problem

 transform: translateY(76%); 

My original site
https://www.phdl.at

pageres screenshot image
![7c7e6d46-7cbb-44c4-9c99-46e11df07bde](https://user-images.githubusercontent.com/5931321/39039742-59c6a350-4486-11e8-8788-b14804f12e97.png)

**Comment by SamVerschueren** [comment]
Sorry, I don't see any difference to be honest. Can you explain what the image should look like then?

**Comment by chandrantwins** [comment]
Please look at the squares.. its white shaded in attached image. But in original image is displayed.

**Comment by unclehking** [comment]
use -webkit-transform not transform
