### ISSUE TITLE
How do I handle promise errors?

### ISSUE THREAD

**Issue by Tolmark12** [sindresorhus/pageres#330]
I'm creating screenshots from a long list of urls. Occasionally a page fails to load, and I'd love to skip it and move onto the next. Currently a load failure causes the whole script to fail. What is the best way to gracefully handle failures? 

I'm currently getting : 
`UnhandledPromiseRejectionWarning: Error: Couldn't load url: http://somesite.com`

**Comment by Strajk** [comment]
@Tolmark12 hey, I'm facing the same issue... have you find some solution please?

**Comment by badgamernl** [comment]
```js
try {
  // Promise code here
} catch (error) {
  console.log(error);
}
```
