### ISSUE TITLE
Render a fake browser window around the screenshot

### ISSUE THREAD

**Issue by rprieto** [sindresorhus/pageres#334]
What do you think of having an option to generate a fake browser window around the screenshot? The result could look like what https://carbon.now.sh does for code:

![image](https://user-images.githubusercontent.com/189105/41799923-93496d82-7673-11e8-85dd-4cad376aee6a.png)

For now I'm automating it like this:
- call Pageres on the target URL, saved as `screenshot.png`
- use a local HTML page that renders an SVG browser window around `<img src="screenshot.png" />`
- call Pageres on that HTML page, which gives the result above

For now it could generate a default browser window, but it also opens the door to custom "skins" like rendering a Windows-style browser, or even a mobile phone (e.g. `--skin macos` or `--skin google-pixel`)

**Comment by sindresorhus** [comment]
It's a cool idea, but I think it's better left to a separate tool.
