### ISSUE TITLE
Pageres cli: Multiple urls, multiple filenames with windows command prompt

### ISSUE THREAD

**Issue by world33** [sindresorhus/pageres#340]
Hi,

How can I generate multiple screenshots each with a customized filename using the windows command prompt which has a limited number of characters than can be pasted (it gets truncated after that limit)?
I would like to create a file with the following strings (just 3 as an example but I have hundreds of urls and custom filenames):
`pageres http://www.upt.al 1200x900 --user-agent="Mozilla/5.0 (Windows NT 6.1; Win64; x64)" --delay=3 --crop --filename=1 pause
pageres http://www.uniel.edu.al 1200x900 --user-agent="Mozilla/5.0 (Windows NT 6.1; Win64; x64)" --delay=3 --crop --filename=2 pause
pageres http://www.unitir.edu.al --user-agent="Mozilla/5.0 (Windows NT 6.1; Win64; x64)" --delay=3 --crop --filename=3 pause`
How can I execute that file in windows command prompt?
I tried to use a .bat file containing those strings but it keeps looping quickly without waiting for each process to finish.
Thanks for any help

**Comment by sindresorhus** [comment]
Use a better command prompt. WSL or http://cmder.net

You could also use the programmatic API in a script and run that.
