### ISSUE TITLE
Throw meaning full error when size is not specified for pageres.src(url, sizes, options)

### ISSUE THREAD

**Issue by sunitJindal** [sindresorhus/pageres#347]
While calling pageres.src, there are 2 parameters which are required i.e. domain and sizes. 

If user do not pass the size this error is thrown:
`TypeError: Cannot read property 'filter' of undefined `

Though the API is correct as it clearly mentiones in the documentation that sizes is required, but can we can throw an error which states something like "sizes is required for pageres.src".

If this makes sense, i'll be happy to create a PR.

**Comment by sindresorhus** [comment]
This was added in v5: https://github.com/sindresorhus/pageres/blob/452e50c33634c3059ea9cac93c146f04fa183598/source/index.ts#L111-L117
