### ISSUE TITLE
feature_request(publish): image hostings support

### ISSUE THREAD

**Issue by Kristinita** [sindresorhus/pageres#358]
### 1. Summary

It would be nice, if pageres can publish website screenshots to external image hostings as Imgur.

### 2. Argumentation

It would be nice use pageres not solely for development; but also to share the site pages to other peoples. It would be nice, if site visitors can quickly and simply view different designs, that use on visited site.

Yes, possible push screenshots folder to services as GitLab/BitBucket/GitHub, but looking at the screenshots is not comfortable for site visitors. Better post screenshots to special image hostings.

#### 3.1. Free

+ [**Official Imgur Community moderator's answer**](https://community.imgur.com/t/how-many-images-can-i-upload-on-my-account/16886/2?u=sashaismygod):

> AFAIK, there’s no limit to how many images you can upload.

Personally:

+ I use Imgur 4 years
+ I have ~2 GB Imgur images

But:

+ I haven't serious problems with Imgur images
+ I haven't paid a cent

#### 3.2. Preview modes

User have option for Imgur album images preview.

+ Vertical — **<https://imgur.com/a/gcIBOrS>**:

![Default](https://i.imgur.com/vF8Uu3N.png)

+ [**Grid thumbnails**](https://community.imgur.com/t/how-can-i-get-a-grid-view-or-horizontal-album-view/51036/2?u=sashaismygod) — **<https://imgur.com/a/gcIBOrS/layout/grid>**:

![Grid thumbnails](https://i.imgur.com/6PzEAEs.png)

+ Embedded — [**Codepen sources**](https://codepen.io/Kristinita/pen/YBoBJq), [**Codepen live demo**](https://codepen.io/Kristinita/full/YBoBJq); nice feature for site designers in `About this site` page:

![Embedded](https://i.imgur.com/97ljNtz.png)

It would be nice to have same previewed modes for site screenshots.

### 4. Example of expected behavior

For [**grunt-pageres options**](https://github.com/sindresorhus/grunt-pageres#options):

```coffee
options:
    # “false” by default
    screenshots_hosting: "Imgur"
    # “false” by default
    # [INFO] https://apidocs.imgur.com/#3f80c836-8f49-4fb1-95a7-a4b058265d72
    api_token: "user_real_api_token"
    # [INFO] Name of remote Imgur album. Create, if no exist.
    # Same value as in “dest” option by default.
    album_name: "screenshots"
    # [INFO] “true” — overwrite remote album, “false” — merge.
    # “false” by default
    overwrite_remote_album: true
```

### 5. About Imgur

+ [**Imgur The Basics**](https://help.imgur.com/hc/en-us/categories/201201803-The-Basics)
+ [**Imgur API**](https://apidocs.imgur.com/)
+ [**node-imgur**](https://github.com/kaimallea/node-imgur)
+ [**TypeScript compatible Imgur client for Node.js**](https://rmp135.github.io/imgur/)

Thanks.

**Comment by bfred-it** [comment]
That's an unrelated feature. You can already combine existing tools like https://github.com/kevva/imgur-uploader-cli and https://github.com/sindresorhus/capture-website-cli

```sh
capture-website https://github.com | imgur-uploader
```
