### ISSUE TITLE
libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by l3l4c7-h4t** [sindresorhus/pageres#359]
Hello
I want to install pageres on centos 6.9
but after run node js, i gave this error:

```
(node:23130) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/test/domains/test.com/public_html/socket/app/node_modules/puppeteer/.local-chromium/linux-624492/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory
```

what is wrong ?

**Comment by sindresorhus** [comment]
The error is coming from `puppeteer`. Try Googling it: https://www.google.com/search?q=puppeteer+centos&oq=puppeteer+centos&aqs=chrome..69i57j69i60l5.1790j0j1&sourceid=chrome&ie=UTF-8

**Comment by l3l4c7-h4t** [comment]
Thanx Sir,
I searched , but some one say `puppeteer` is not support on centos 6.9 anymore :(

it's true ?

**Comment by prasanthsriram** [comment]
you can install **sudo yum install atk java-atk-wrapper at-spi2-atk gtk3 libXt** on your centos machine, to run the chrome headless function.
