### ISSUE TITLE
Set chromium flags?

### ISSUE THREAD

**Issue by DaveSeidman** [sindresorhus/pageres#365]
Is it possible to set chromium flags before screenshooting? Specifically I'd like to set:
`chrome://flags/#autoplay-policy` to `no-gesture-is-required` so that videos will appear in the screenshots. I'm running my server on localhost if that helps.

**Comment by sindresorhus** [comment]
Not at the moment. We could add `launchOptions` option that would be passed to https://github.com/sindresorhus/capture-website#launchoptions (which is the underlying library). You could then set `args` in `launchOptions`.

I'm not sure exactly how `no-gesture-is-required` should be passed, but this might help: https://stackoverflow.com/questions/50607866/setting-specific-chrome-flags-in-puppeteer-enable-and-disable?rq=1

We could also consider having a `featureFlags` option to make it easy to toggle feature flags, but not sure how difficult that would be.

**Comment by DaveSeidman** [comment]
Thanks, that pointed me in the right direction! I still ended up having to swap in Chrome for Chromium to get video playback working. Unfortunately that launches a "Welcome to Google Chrome" dialog that must be manually closed each time so now looking into how to suppress that.

**Comment by sindresorhus** [comment]
Maybe https://peter.sh/experiments/chromium-command-line-switches/#no-first-run

**Comment by DaveSeidman** [comment]
That fixed it! Thank you so much!
