### ISSUE TITLE
Chromium revision is not downloaded. Run npm install

### ISSUE THREAD

**Issue by usfslk** [sindresorhus/pageres#366]
My app is a node server. It works well locally. The full error message I am getting is:

> Failed to launch chrome!\n[0423/034123.356516:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

Code I am using

```
new Pageres({ delay: delay, filename: filename })
    .src(url, [dimensions])
    .dest('./data/')
    .run()
    .then(function () { ... }
```

I tried both zeit now and heroku, same error.

**Comment by zhuyinjing** [comment]
@usfslk  this question has solved??

**Comment by alflanagan** [comment]
Note the error message in the title of this issue is unrelated to the actual problem reported. Someone with access should update it, or possibly close it, since the answer is contained in the question.
