### ISSUE TITLE
Full Height Screenshots

### ISSUE THREAD

**Issue by Ethanhackett** [sindresorhus/pageres#368]
It would be really helpful if we could pass sizes like [1024x-] and maybe load the page get body height or something and then reload the browser as 1024xBODYHEIGHT for a full page screenshot? I know it's more complex but it would reduce the overhead of maintaining a set height for each page of the screenshot etc. It would also allow for the screenshot too to be height agnostic.

Other than that I'm loving this!

**Comment by Ethanhackett** [comment]
Aw I set it up incorrectly the first time. Now it's generating full screens.

**Comment by a613** [comment]
Do you remember what you changed?

**Comment by JugglerX** [comment]
how do you capture full height?
