### ISSUE TITLE
Pages with Javascript

### ISSUE THREAD

**Issue by AlmogCohen** [sindresorhus/pageres#369]
Looks pretty awesome everything here and the level of maintainability even better than awesome! I was looking around but couldn't figure out if the pageres takes pictures of JavaScript-rendered objects or XHR based in the target URLs.

Sorry if it should have been obvious from the readme or anywhere else :) Thanks!

**Comment by sindresorhus** [comment]
It takes picture of the website as if you had gone to the website in Chrome and taken a screenshot. So to answer you question, yes.

**Comment by AlmogCohen** [comment]
Awesome!!! Thanks :)
