### ISSUE TITLE
How to pass `--no-sandbox` argument to puppeteer?

### ISSUE THREAD

**Issue by posrix** [sindresorhus/pageres#374]
For dealing with `No usable sandbox` issue

**Comment by posrix** [comment]
@sindresorhus seems there's no any explain about puppeteer argument in README?

**Comment by sindresorhus** [comment]
It's explained at the top of the readme:

> Note to Linux users: If you get a "No usable sandbox!" error, you need to enable [system sandboxing](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox).

**Comment by posrix** [comment]
> If you absolutely trust the content you open in Chrome, you can launch Chrome with the --no-sandbox argument:

> const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});

I mean this solution, how could i do it?

**Comment by jisaf** [comment]
@posrix any chance you figured this out? Thanks

**Comment by inbaz** [comment]
If somebody finds this issue. I've managed to set --no-sandbox by editing node_modules/capture-website/index.js:143 from:
```
        launchOptions: {},
```
to:
```
        launchOptions: {args: ['--no-sandbox', '--disable-setuid-sandbox']},
```
