### ISSUE TITLE
Unable to use absolute filename with pageres-cli

### ISSUE THREAD

**Issue by imcaizheng** [sindresorhus/pageres#375]
OS: Linux
pageres-cli version: 5.0.0

The following command returns an error.

```bash
pageres https://www.booleanworld.com/take-screenshots-webpages-command-line/ --filename /tmp/screenshot

{ Error: ENOENT: no such file or directory, open '/home/aaron/tmp/screenshot.png'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/aaron/tmp/screenshot.png' }
```

It seems like that `pageres` always prefixes the cwd to the filename even if the filename starts with a backslash character.

**Comment by sindresorhus** [comment]
The `filename` options is supposed to be a filename, not a file path.
