### ISSUE TITLE
Update dependencies - npm audit

### ISSUE THREAD

**Issue by stardines** [sindresorhus/pageres#380]
![Screenshot 2019-12-13 at 1 18 02 PM](https://user-images.githubusercontent.com/529999/70780671-1361a180-1dab-11ea-8a48-132fe52ef2c0.png)

**Comment by garyray-k** [comment]
https://github.com/kevva/get-res/issues/2#issue-609795196

beginning to trickle the issue down to appropriate package owner.

**Comment by garyray-k** [comment]
https://github.com/cheeriojs/cheerio/issues/1346#issue-488341068

**Comment by sindresorhus** [comment]
Dependencies updated in https://github.com/sindresorhus/pageres/releases/tag/v7.0.0
