### ISSUE TITLE
Add Support for list of Domains

### ISSUE THREAD

**Issue by attacker34** [sindresorhus/pageres#382]
Dear @macx 

Please add support for the list of domains/subdomains along with option of using only one or two domains for using screenshot function.Like if i don't wanna use my list of domains/subdomains against 10 different websites but only 1 or 2 websites.

Sincerely,

**Comment by sindresorhus** [comment]
Not clear to me what you're asking for exactly. Could you include an example of how you would use this feature that your asking for?

**Comment by attacker34** [comment]
@sindresorhus sorry for the confusion.... I've two requests:

1. Add support for list of domains like domains_list.txt
2. Add support for choosing number of sites (by default, your tool fetches screenshots from 10 different sites) from which our subdomain.txt will fetch screenshots.

To explain more,  You've 10 different sites from where you fetches screenshots.For example these sites are used for fetching screenshots:

1. url2png.com
2. url2jpeg.com
3.
4.

List ends at 10. 

So, I wanna use only one or two sites for fetching screenshots.

I hope its clear now?

Thanks !!

**Comment by sindresorhus** [comment]
It's still not clear. Are you talking about the Pageres API or the CLI? Maybe if you provide a code example on exactly how it would look to use Pageres if what you're asking would have already been implemented.

**Comment by sindresorhus** [comment]
> by default, your tool fetches screenshots from 10 different sites

Pageres does not fetch from 10 different sites by default, so I'm confused.

**Comment by attacker34** [comment]
![Screen Shot 2020-01-07 at 10 16 54 PM](https://user-images.githubusercontent.com/10330087/71914233-fc8c5000-319a-11ea-8e81-e7305c2e02b1.png)

@sindresorhus  Please check this.

**Comment by sindresorhus** [comment]
That just describes how fast it is.

**Comment by chrismccoy** [comment]
think he means pass a text file of urls

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/pageres/issues/383.
