### ISSUE TITLE
Unable to run pageres-cli via cron job

### ISSUE THREAD

**Issue by billdennen** [sindresorhus/pageres#384]
Hi - I have a shell script that runs pageres-cli. The shell script runs fine from the command line, but when I try to run it via cron, I get:

env: node: No such file or directory

any way to make this work via cron? thanks.

**Comment by billdennen** [comment]
I change the first line of the pageres script 

from:
#!/usr/bin/env node

to:
#!/usr/bin/env /usr/local/bin/node

and this seems to have solved the problem.

**Comment by sindresorhus** [comment]
That is not the correct fix. You need to ensure `node` is in your PATH. This has nothing to do with Pageres though. Google is your friend ;)
