### ISSUE TITLE
Version 4 fails and version 5 hangs

### ISSUE THREAD

**Issue by tonsV2** [sindresorhus/pageres#388]
I'm trying to execute the below command.

`./node_modules/.bin/pageres https://www.facebook.com/LundtofteBoldklub/ 400x600 --selector=div.userContentWrapper:first-of-type --filename=lundtofte-boldklub2`

Version 4 simply prints the following error

`Couldn't load url: https://www.facebook.com/LundtofteBoldklub/`

Version 5 just hangs.

I've tried this on Fedora 32, Fedora 30 and on Docker using node:8.

Any clue about how to make this work? Please let me know if I should supply any additional 
information.

**Comment by sindresorhus** [comment]
It's probably waiting for the selector you specified and that selector never matches.

**Comment by mikelehen** [comment]
FWIW- the docs say there's a default timeout of 60 seconds, but it doesn't in fact seem there is.  This caused me a bunch of confusion and debugging headaches until I realized that I needed to manually set a timeout.
