### ISSUE TITLE
Recommended Settings for Performance? PhantomJS was faster by 40% - 60%

### ISSUE THREAD

**Issue by tomerb15** [sindresorhus/pageres#398]
I'm using the latest version of this great NPM for converting small and trusted HTMLs to jpg/png.
My goal is to complete the conversion as fast as possible.

My question is how can we setup `pageres` for the high performance?

Can we reuse the same `puppeteer` instance?
Should we configure puppeteer / headless chrome differently?

We used to do the same before moving to puppeteer and with Phantom JS it was faster by 40% - 60%.

**Comment by sindresorhus** [comment]
I'm going to assume you're already using `Promise.all` for maximum concurrency. The next step would be for Pageres to support process pooling so the Puppeteer instance could be reused. That's not yet supported though. https://github.com/sindresorhus/pageres/issues/284
