### ISSUE TITLE
How to add Puppeteer's launch option [--no-sandbox] to Pageres constructor?

### ISSUE THREAD

**Issue by Simao-Santos** [sindresorhus/pageres#402]
We need to not use sandbox in our project, but we can't seem to specify it. We don't use "puppeteer.launch" per se, we just initialize with the Pageres constructor.

Thanks in advance!

**Comment by sindresorhus** [comment]
No option for this yet. You could use https://github.com/sindresorhus/capture-website instead if you need more options right now.

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/pageres/releases/tag/v6.1.0
