### ISSUE TITLE
Help, does anyone have any examples created with the Lua programming language?

### ISSUE THREAD

**Issue by nodecentral** [sindresorhus/pageres#406]
Hi

I’m learning Lua and would like to try out some example of pageres, but I’m struggling with understanding the api 
Does anyone have any Lua api call examples they could share ?

Many thanks in advance

**Comment by sindresorhus** [comment]
This is not the place to ask Lua questions. Pageres is a Node.js library and a command-line tool, which has nothing to do with Lua.

**Comment by nodecentral** [comment]
Ok sure, ultimately my goal is to find some good examples - as the Lua language is just the wrapper to make use of them.

I’ll tie it into this one then - https://github.com/sindresorhus/pageres/issues/321 which does not seem to have made any progress..
