### ISSUE TITLE
Installation problem with MacOS M1 chip

### ISSUE THREAD

**Issue by shinokada** [sindresorhus/pageres#420]
I get the following errors on macOS M1 chip. Is there any workarounds to solve this?

```
$ npm install --global pageres-cli

/Users/shinichiokada/.nvm/versions/node/v14.17.6/bin/pageres -> /Users/shinichiokada/.nvm/versions/node/v14.17.6/lib/node_modules/pageres-cli/cli.js

> puppeteer@5.5.0 install /Users/shinichiokada/.nvm/versions/node/v14.17.6/lib/node_modules/pageres-cli/node_modules/puppeteer
> node install.js

The chromium binary is not available for arm64:
If you are on Ubuntu, you can install with:

 apt-get install chromium-browser

/Users/shinichiokada/.nvm/versions/node/v14.17.6/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112
            throw new Error();
            ^

Error
    at /Users/shinichiokada/.nvm/versions/node/v14.17.6/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112:19
    at FSReqCallback.oncomplete (fs.js:192:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@5.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@5.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shinichiokada/.npm/_logs/2021-09-27T03_28_58_027Z-debug.log
```

**Comment by hyyper** [comment]
sudo npm install pageres --unsafe-perm

**Comment by hyyper** [comment]
`sudo npm install pageres-cli --unsafe-perm`

**Comment by bigflannel** [comment]
Its May 2022. I failed several months ago to get pageres working on my silicon M1 iMac with Big Sur. It seemed like it would all get resolved. I tried to install again just now and failed. I uninstalled pageres, pageres-cli, puppeteer (using npm). I updated node, I updated npm, I updated brew. I have node v18.1.0, npm 8.8.0. I re-installed pageres, then pageres-cli which failed with error chromium binary not available. I installed chromium using Brew, when I went to launch chromium, it said the application was damaged, I unlocked it from the terminal with xattr -cr /applications/chromium.app. I installed pageres-cli again, I added this to my .zshrc file export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true export PUPPETEER_EXECUTABLE_PATH=`which chromium` and eventually pageres runs but fails with an error:

Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT

I manually updated puppeteer, uninstalled and reinstalled pageres and pagres-cli. But I get the same error.

I've searched and searched, I've done what everybody else seems to be doing, but I can't get it to work.

Any advice greatly appreciated!

Regards
Mike

**Comment by bigflannel** [comment]
Hm. I downgraded to node 12, based on a post on this thread, and it worked after installing pageres and pageres-cli again.

https://stackoverflow.com/questions/59979188/error-failed-to-launch-the-browser-process-puppeteer

I have no idea why.

Regards
Mike

**Comment by honzajavorek** [comment]
Looks like it has something to do with https://github.com/puppeteer/puppeteer/issues/6622, https://github.com/puppeteer/puppeteer/pull/6495, etc. I think upgrading pupeteer (transitively also capture-website) would solve it.

For those using the library as it is, passing the correct path to the chromium binary to [launchOptions](https://github.com/sindresorhus/pageres#launchoptions) should solve it. For those using the pageres-cli (such as me) I don't think there's any hope as of now.

**Comment by sindresorhus** [comment]
Try the latest version: https://github.com/sindresorhus/pageres/releases/tag/v7.0.0 It may have resolved the issue.
