### ISSUE TITLE
Update version of capture-website

### ISSUE THREAD

**Issue by ropel** [sindresorhus/pageres#421]
This library includes an old version of capture-website, missing the last fixes, including try-catch on page/browser open and close.
This causes memory leaks and tons of chrome processes when something goes wrong

**Comment by connected201** [comment]
Hi, [TypeScript 4.6.2](https://github.com/microsoft/TypeScript/releases/tag/v4.6.2) released

**Comment by sindresorhus** [comment]
The required feature was deferred to TS 4.7, so this is still blocked.

**Comment by mehedi-sharif** [comment]
@connected201 [TypeScript 4.7.4](https://github.com/microsoft/TypeScript/releases/tag/v4.7.4) released

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/pageres/releases/tag/v7.0.0
