### ISSUE TITLE
Support beforeScreenshot option

### ISSUE THREAD

**Issue by jopemachine** [sindresorhus/pageres#424]
It seems like [capture-website](https://github.com/sindresorhus/capture-website)'s some options including `beforeScreenshot` is missing from the [finalOptions](https://github.com/sindresorhus/pageres/blob/main/source/index.ts#L481-L498).

I think supporting `beforeScreenshot` option could be useful when the website stores access token in the localstorage. (or other situations) like below way.

Do you have any plans to add capture-website's other options including beforeScreenshot?

```js

// Ref : https://stackoverflow.com/questions/51789038/set-localstorage-items-before-page-loads-in-puppeteer
const setLocalStorageToken = (page) => {
  await page.evaluate(() => {
    localStorage.setItem('token', 'example-token');
  });

  // user token set successfully.
  await page.goto('http://localhost:8080/');
};

(async () => {
  await new Pageres({
    delay: 2,
    beforeScreenShot: (page) => {
      setLocalStorageToken(page);
    }
  })
    .src('http://localhost:8080/')
    .dest(__dirname)
    .run();

  console.log('Finished generating screenshots!');
})();
```

I appreciate all your efforts in creating and maintaining these awesome libraries.

**Comment by sindresorhus** [comment]
It's not something I plan to work on, but a good pull request would be welcomed. Should be easy enough to copy-paste the docs from `capture-website`.
