### ISSUE TITLE
pageres stuck

### ISSUE THREAD

**Issue by connected201** [sindresorhus/pageres#429]
hi, pageres freeze when in browser i receive this message:
![image](https://user-images.githubusercontent.com/20506433/158075608-3a3ea5c3-f633-4083-a65f-16d3c7993e66.png)
How to bypass?
UPD, i tested on `pageres-cli` also when i have popup openned, page loop loading and wait to push OK

**Comment by sindresorhus** [comment]
Try the latest version: https://github.com/sindresorhus/pageres-cli/releases/tag/v7.0.0 It may have resolved the issue.
