### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by DNAScanner** [sindresorhus/pageres#433]
Hello, for a project im working on I need to take a screenshot of a website and execute some js on the website before capturing the site. So I put some testing script code into the request, but it doesn't work somehow. The code doesn't get executed.
Code:
```js
await new pageres({delay: 2, script: `document.body.innerHTML = ""`})
	.src(translationUrl, ["1920x1080"], {filename: `${imageId}`})
	.dest("./images/")
	.run();
```

[Image being returned](https://media.discordapp.net/attachments/1013873444527542413/1013881074461462598/Asd.png)

**Comment by sindresorhus** [comment]
This seems to work in the latest version for me: https://github.com/sindresorhus/pageres/releases/tag/v7.0.0 (just released)

**Comment by DNAScanner** [comment]
Im not that good with node, what do I have to do?
![image](https://user-images.githubusercontent.com/75182303/187404799-ccc21d37-a7bb-4df3-b44b-a5de3e731ef8.png)
Ive tried doing this, but it doesn't work
```js
import {pageres} from "pageres";
```

**Comment by DNAScanner** [comment]
Nvm, just had a typo. Works now
