### ISSUE TITLE
Package Update

### ISSUE THREAD

**Issue by peter-miroshnikov** [sindresorhus/pageres#436]
Hello,

I am using your tool inside Github CI/CD Pipelines and .... github just updated their Chromium version to `106.0.5235.0`
Sadly your tool uses Puppeteer that requires the previous version of Chromium, thus now we hit a wall.

Do you plan any updates on your packages soon or should we fork and make a pr ?

Cheers

**Comment by sindresorhus** [comment]
Done in https://github.com/sindresorhus/pageres/releases/tag/v7.1.0

**Comment by sindresorhus** [comment]
However, depending on the system version to match this package seems very fragile. I cannot update this package every time a new Puppeteer version is out.
