### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by hced** [sindresorhus/pageres#54]
Running the example command …

``` zsh
❯ pageres todomvc.com yeoman.io 1366x768 1600x900
```

Gives this error:

``` zsh
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

And …

``` zsh
❯ sudo !!
```

… gives the following warning:

``` zsh
You are not allowed to run this app with root permissions.
If running without sudo doesn't work, you can either fix your permission problems or change where npm stores global packages by putting ~/npm/bin in your PATH and running:
npm config set prefix ~/npm
```

… in which I did the latter part, i.e. adding `~/npm/bin` in my `$home` (had to create the directory) and include it in my `$PATH`.

Still the same error. Any clues?

---
##### Versions of binaries

node 0.10.24
npm 1.3.21
pageres 0.2.3
phantomjs 1.9.7 (The one that came as a dependency when installing pageres)
##### OS

Mac OS X 10.9.1

**Comment by diego-vieira** [comment]
@thomasklemm fix worked for me.

**Comment by priyankachaturvedi** [comment]
for those who are still stuck in this,It is just the access problem.
phantomjs may not be working on your system, check it by writing phantomjs --v in terminal.
make your phantomjs work properly and the error will be gone :)

**Comment by sank64** [comment]
Bad but efficient method:
Edit pageres/cli.js by removing the line "sudoBlock();"
Save.

**Comment by kevva** [comment]
@sank64, it's bad practice to use `sudo` with npm.
