### ISSUE TITLE
PhantomJS 2

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pageres#77]
The current WebKit in PhantomJS is ancient. We should upgrade to PhantomJS 2 as soon as it is available. Hopefully within this month or next.

https://groups.google.com/forum/#!topic/phantomjs/z6Xy1f0Xqhc

-

This is currently blocked by the PhantomJS 2.0 release being broken... We have to wait for the `phantomjs` module to upgrade: https://github.com/Medium/phantomjs/issues/288

**Comment by kevva** [comment]
Getting closer https://github.com/ariya/phantomjs/issues/12897.

**Comment by hagerhink** [comment]
PhantomJS is now 2.0: http://phantomjs.org/release-2.0.html

**Comment by kevva** [comment]
There's still no Linux binary.

**Comment by th3m4ri0** [comment]
:sob: My border-radiuses are sooooo square.

**Comment by skullcrasher** [comment]
+1

**Comment by skullcrasher** [comment]
Is there any possibility that I can use my selfcompiled phantomjs 2.0 with pageres? Until an official binary exists.

**Comment by kevva** [comment]
Install this and replace the one somewhere in `node_modules` with a symlink to your binary.

**Comment by skullcrasher** [comment]
Thanks for the hint. Just tested and it works perfect so far.

**Comment by ingro** [comment]
Maybe it will be easier adding an options to specify a custom phantomjs binary path?

**Comment by diegoaguilar** [comment]
@kevva Where is that file I should replace with a symlink exactly?

**Comment by kevva** [comment]
@diegoaguilar, somewhere in `node_modules/phantomjs` I think.

**Comment by jvandemo** [comment]
I managed to get it working using PhantomJS 2 like this:

STEP 1: Download and extract PhantomJS 2 from [https://github.com/eugene1g/phantomjs/releases](https://github.com/eugene1g/phantomjs/releases)

STEP 2: From the extracted files, move PhantomJS 2 binary to your /usr/local/bin

```bash
# Optional, backup old version first
$ mv /usr/local/bin/phantomjs /usr/local/bin/_phantomjs

# Copy PhantomJS 2 binary
$ cp phantomjs /usr/local/bin
```

STEP 3: Link your pageres phantomjs to the new binary:

```bash
# Go to directory where pageres bin is stored
$ cd /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/screenshot-stream/node_modules/phantom-bridge/node_modules/phantomjs/lib/phantom/bin/

# Backup previous version
$ mv phantomjs _phantomjs

# Link to new PhantomJS 2 binary
$ ln -s /usr/local/bin/phantomjs phantomjs
```

Pageres should now use PhantomJS 2 and support flexbox!

**Comment by th3m4ri0** [comment]
@kevva would Ubuntu binary work ? https://github.com/eugene1g/phantomjs/releases/tag/2.0.0-bin

**Comment by kevva** [comment]
Ask here https://github.com/Medium/phantomjs/issues/288.

**Comment by brunowego** [comment]
+1
