### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pageres#83]
It's already pretty fast, but we did get a drop in perf when switching from PhantomJS writing directly to disk and using streams over stdio with base64 decoding instead.

Look into whether there's any way to improve this. I wonder if we could convince the PhantomJS people to add the ability to do binary directly over stdio instead of having to encode/decode base64.

Another things we could explore is to reuse a socket for the same size but different sizes and rather resize the phantomjs window instead of starting up a new process for each. Phantomjs is really slow to start up. Not sure if this would improve perf though, since we currently parallelize a lot it might not matter.

Other suggestions welcome :)

**Comment by a1Gupta** [comment]
Any updates on it ? How queue can be used with pageres to access multiple websites(limited) and generate their screenshot

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/pageres/issues/284.
